### ISSUE TITLE
Varias Dudas de la API Bodega y Fábrica

### ISSUE THREAD

**Issue by nivek0o0** [IIC3103/2019-proyecto#1]
Hola, 
1. ¿El `oc` (id de orden de compra) lo inventamos y manejamos nosotros?
2. ¿Cuál es la diferencia entre `productoId` y `sku`? ¿Por qué tenemos que manejar ambos?
3. ¿Cómo se transfiere dinero a la cuenta de la fábrica? ¿Cómo se transfiere dinero a la cuenta de otro grupo?
4. ¿Cómo sabemos cuál es nuestra cuenta y el dinero que tenemos?
5. ¿En el hook de recepción de productos recibiremos productos desde la fábrica?
6. ¿Cómo consultamos a la fábrica nuestras solicitudes para saber si ya fueron despachadas o no?
7. ¿Está funcionando la API? Al consultar los almacenes me devuelve `Cannot GET /almacenes`

**Comment by arturokunder** [comment]
Hola Kevin,
Te respondo por cada uno de los puntos:

1. El `id` de la orden de compra (oc) es un string en formato `ObjectId`. De la [documentación](https://docs.mongodb.com/manual/reference/method/ObjectId/):
```
The 12-byte ObjectId value consists of:
- a 4-byte value representing the seconds since the Unix epoch,
- a 5-byte random value, and
- a 3-byte counter, starting with a random value.
```
Ejemplo: `507f191e810c19729de860ea`

Las órdenes de compra no las usaremos en esta entrega. A partir de la entrega 2, las ventas de productos se realizarán por medio de órdenes de compra.

2. El `product_id` es el identificador único de la instancia de un producto, mientras que el `sku` el identificador del tipo de producto. Por ejemplo, el sku 10 podría representar arroz, mientras que el sku 2367 podría representar salmón ahumado.
De la documentación:
```js
{
   "_id": "4af9f23d8ead0e1d32000002",
   "sku": "10",
   "almacen": "4af9f23d8ead0e1d32000000",
   "costo": 0,
   "grupo": 1,
   "despachado": true,
   "precio": 1990,
   "direccion": "direccion de envio",
   "oc": "4af9f23d8ead0e1d32000900",
   "vencimiento": 1493215000000
}
```
En este caso, el sku es `10`, mientras que el `id` es `4af9f23d8ead0e1d32000002`.
Puedes tener muchos productos con sku `10` pero nunca un `id` repetido

3. Para esta entrega no hay que realizar transferencias a la fábrica. Eso se maneja en el sistema de banco. En esta entrega, pueden usar el método [Fabricar sin Pago](https://integracion-2019-dev.herokuapp.com/bodega/docs/#api-Fabrica-PutFabricaFabricarsinpago)

4. Lo maneja el sistema de banco, que no usaremos en esta entrega.

5. No lo usaremos en esta entrega. Para fabricar cualquier producto, basta con que invoquen [Fabricar sin Pago](https://integracion-2019-dev.herokuapp.com/bodega/docs/#api-Fabrica-PutFabricaFabricarsinpago)

6. A que te refieres? Para saber si ya se fabricó?

7. La API aún no está arriba. Tengo que crear los grupos, productos y darles las credenciales de acceso, después de esta pre-entrega de los servicios

**Comment by nivek0o0** [comment]
Hola, gracias por la rápida respuesta.

En la 6 me refería a cómo podemos saber si la fabricación ya está lista. En la documentación uno de los atributos retornados dice `Fecha aproximada cuando los productos a fabricar estarán disponibles`, lo que sugiere que hay variabilidad.

Respecto al mismo tema tengo otra pregunta.
8. ¿La fábrica despacha automáticamente a nuestro almacén de recepción?

**Comment by arturokunder** [comment]
Efectivamente, en la 6 hay un tiempo de espera para obtener los productos enviados a fábrica.
Además, existe cierta variabilidad (bastante baja) en el cumplimiento de la fecha esperada

Respecto del 8, si, la fábrica despacha automáticamente apenas la fabricación está lista.
