### ISSUE TITLE
ObjectId data type

### ISSUE THREAD

**Issue by cjgazali** [IIC3103/2019-proyecto#10]
En la documentación aparece ObjectId como tipo de dato, y lo pusimos para el almacenId en nuestras APIs. De repente noté que no conocía este tipo.
- ObjectId es un tipo de MongoDB, ¿correcto?
- Cuando pregunto su tipo en una respuesta de la API docente, me dice que es string. En la documentación de nuestras APIs, ¿Es lo mismo decir ObjectId que string, en la práctica? ¿Podemos tratarlos siempre como strings?
- ¿Tienen un largo máximo? En la documentación he visto de 24 y de 25.
- Esto es similar a que Object[] es en la práctica una lista de diccionarios, ¿correcto?

Gracias!

**Comment by arturokunder** [comment]
Efectivamente la API responde el ObjectId en formato `string`, ya que este formato no es soportado por los objetos `JSON`.
Respecto del largo, la documentación dice lo siguiente:

> The 12-byte ObjectId value consists of:
> - a 4-byte value representing the seconds since the Unix epoch,
> - a 5-byte random value, and
> - a 3-byte counter, starting with a random value.

Así que realidad, más que el largo de 24/25, corresponde a 12 bytes
De todas formas, eso debería corresponder a `string` de largo 24. 
Donde viste el `string` de largo 25?
