### ISSUE TITLE
Fabricar Producto 10003

### ISSUE THREAD

**Issue by dalliende** [IIC3103/2019-proyecto#100]
Hemos tenido problemas para crear algunos rolls en particular los que contienen masago. Nos llego una OC para el sku 10003 y nuestra aplicación no la pudo despachar ni fabricar correctamente. Por esto probamos manualmente y el postman nos arrojo lo siguiente:

![WhatsApp Image 2019-06-26 at 01 39 58](https://user-images.githubusercontent.com/11409081/60154226-a20a4400-97b4-11e9-882c-1ea339d39a8f.jpeg)

Cual podria ser el problema? 

Saludos

**Comment by jtagle2** [comment]
Me pasaba lo mismo. Si te fijas, en esa respuesta te muestra solo 4 ingredientes, y el sku 10003 necesita 6. Lo que no muestra en la lista, son los ingredientes que no tienes suficientes (Revisa tus niveles de stock de 1201 y 1105, que son los dos productos que según la API no tienes).

@arturokunder, no sé si esto es un bug o si está bien que esa sea la respuesta. Pero quizás para otros semestres sería bueno cambiarla, o bien poner un disclaimer advirtiendo el funcionamiento de la respuesta a cocinar/fabricar cuando no se tienen todos los productos, porque hay varios grupos (me incluyo en la famosa #71 jajaja) que perdimos harto tiempo debugueando este mismo problema.

**Comment by arturokunder** [comment]
Ahora entiendo bien!
Muchas gracias @jtagle2 por la sugerencia. De todas formas la implementaré. 
Claramente la idea de esa respuesta era entregar información útil.

@dalliende pudiste resolver el problema?

Arturo

**Comment by svergara1** [comment]
Y ojo @dalliende que si no tienes todos los ingredientes necesarios en cocina e intentas cocinar, te va a tirar error pero igual se va a llevar todos esos ingredientes que estaban en cocina (#88 ). Nos dimos cuenta tarde que la API estaba implementada así y nos costó caro para le entrega 2..

**Comment by dalliende** [comment]
Si lo pude resolver era una mezcla entre lo que comento svergara1 y joaquin. 

Gracias
