### ISSUE TITLE
La API se comió nuestros productos finales

### ISSUE THREAD

**Issue by nivek0o0** [IIC3103/2019-proyecto#101]
Grupo 5, Aproximadamente a las 10:10 despachamos 2 órdenes de compra FTP:

|                  OC                        |   sku   | cantidad |
|:-------------:|:-------------:|:-----:|
| 5d136cbc99c2fd0004e7b825 | 10008 | 1 |
| 5d136cbc99c2fd0004e7b824 | 10013 | 3 |

La primera está como **finalizada**, pero la otra quedó en **aceptada** y las 3 unidades desaparecieron! (Esas 3 unidades fueron mandadas a fabricar a las 09:06:36 aprox. y llegaron como a las 09:46, que por cierto es totalmente inconsistente al tiempo esperado producción del Excel)

Estamos 100% seguros que teníamos las 4 unidades en cocina. Queremos saber qué pasó con esa `oc` y con los productos.

Gracias

**Comment by arturokunder** [comment]
Kevin, tranquilo.  La api no se ha comido nada. La orden se demora un poco en quedar marcada como finalizada.
Este es el estado actual de la oc (finalizada):

```json
{
    "_id": {
        "$oid": "5d136cbc99c2fd0004e7b824"
    },
    "created_at": {
        "$date": "2019-06-26T13:01:48.824Z"
    },
    "updated_at": {
        "$date": "2019-06-26T15:51:40.785Z"
    },
    "cliente": "distribuidor",
    "proveedor": "5cc66e378820160004a4c3c0",
    "sku": "10013",
    "urlNotificacion": "",
    "estado": "finalizada",
    "fechaDespachos": [],
    "fechaEntrega": {
        "$date": "2019-06-26T14:31:00.000Z"
    },
    "precioUnitario": 5700,
    "cantidadDespachada": 3,
    "cantidad": 3,
    "canal": "ftp",
    "__v": 0
}
```

Y los productos que enviaste asociados a este oc:
```json
[{
    "_id": {
        "$oid": "5d13920b55bdc80004e67d61"
    },
    "sku": "10013",
    "costo": 0,
    "grupo": 5,
    "despachado": true,
    "precio": 1,
    "direccion": "cualquiera",
    "oc": {
        "$oid": "5d136cbc99c2fd0004e7b824"
    },
    "vencimiento": {
        "$date": "2019-06-26T16:41:06.460Z"
    },
    "almacen": {
        "$oid": "5cc7b139a823b10004d8e6e6"
    },
    "fechaDespacho": {
        "$date": "2019-06-26T15:46:50.216Z"
    }
},{
    "_id": {
        "$oid": "5d13920b55bdc80004e67d62"
    },
    "sku": "10013",
    "costo": 0,
    "grupo": 5,
    "despachado": true,
    "precio": 1,
    "direccion": "cualquiera",
    "oc": {
        "$oid": "5d136cbc99c2fd0004e7b824"
    },
    "vencimiento": {
        "$date": "2019-06-26T16:41:06.460Z"
    },
    "almacen": {
        "$oid": "5cc7b139a823b10004d8e6e6"
    },
    "fechaDespacho": {
        "$date": "2019-06-26T15:47:14.231Z"
    }
},{
    "_id": {
        "$oid": "5d13920b55bdc80004e67d63"
    },
    "sku": "10013",
    "costo": 0,
    "grupo": 5,
    "despachado": true,
    "precio": 1,
    "direccion": "cualquiera",
    "oc": {
        "$oid": "5d136cbc99c2fd0004e7b824"
    },
    "vencimiento": {
        "$date": "2019-06-26T16:41:06.460Z"
    },
    "almacen": {
        "$oid": "5cc7b139a823b10004d8e6e6"
    },
    "fechaDespacho": {
        "$date": "2019-06-26T15:47:37.852Z"
    }
}]
```

Respecto de la fábrica, recuerda que el excel es el valor esperado, y hay variabilidad respecto a ese valor.

**Comment by nivek0o0** [comment]
Profesor, esa orden la finalizamos hace media hora desde postman (tuvimos que producir los rolls de nuevo) Esto no quita que haya fallado a las 10:10 hrs.

Le ruego revisar nuevamente los registros de su BD en la hora que falló. (No debe ser dificil buscar esos 3 productos de sku 10013, porque los producimos solo cuando nos lo pide la prden)

**Comment by arturokunder** [comment]
aa ok, ahora entiendo.
Efectivamente hay 6 productos para ese sku, así que fueron fácil de encontrar.
A las 10:10 no falló. Los productos ya estaban vencidos, y por tanto, no los podías despachar (las horas de los objetos están en UTC, es decir, debes restarle 4 hrs para obtener la hora chilena).

```json
[{
    "_id": {
        "$oid": "5d136f1214bf800004db70d0"
    },
    "sku": "10013",
    "costo": 0,
    "grupo": 5,
    "despachado": false,
    "precio": 0,
    "direccion": "",
    "oc": null,
    "vencimiento": {
        "$date": "2019-06-26T14:07:02.566Z"
    },
    "almacen": {
        "$oid": "5cc7b139a823b10004d8e6ea"
    }
},{
    "_id": {
        "$oid": "5d136f1214bf800004db70d1"
    },
    "sku": "10013",
    "costo": 0,
    "grupo": 5,
    "despachado": false,
    "precio": 0,
    "direccion": "",
    "oc": null,
    "vencimiento": {
        "$date": "2019-06-26T14:07:02.566Z"
    },
    "almacen": {
        "$oid": "5cc7b139a823b10004d8e6ea"
    }
},{
    "_id": {
        "$oid": "5d136f1214bf800004db70d2"
    },
    "sku": "10013",
    "costo": 0,
    "grupo": 5,
    "despachado": false,
    "precio": 0,
    "direccion": "",
    "oc": null,
    "vencimiento": {
        "$date": "2019-06-26T14:07:02.566Z"
    },
    "almacen": {
        "$oid": "5cc7b139a823b10004d8e6ea"
    }
}]
```

**Comment by arturokunder** [comment]
pd: los 3 productos fueron creados el 2019-06-26 a las 13:11:46.000Z
La fecha de creación la puedes obtener [decodificando](https://steveridout.github.io/mongo-object-time/) el `_id` .
