### ISSUE TITLE
Error 404 "sku no encontrado" al Fabricar productos sin pago

### ISSUE THREAD

**Issue by aurodriguez** [IIC3103/2019-proyecto#12]
Al intentar fabricar cualquier producto al utilizar el método fabricar sin pago, independiente del SKU que utilice, obtenemos siempre la respuesta 404 "sku no encontrado".

Y este mensaje enviado se le aplica al hash, como se especifica en la documentación:

<img width="634" alt="Screen Shot 2019-04-25 at 12 27 13" src="https://user-images.githubusercontent.com/28511788/56752113-9323f880-6755-11e9-8d4b-6e5da265cb24.png">

<img width="635" alt="Screen Shot 2019-04-25 at 12 28 20" src="https://user-images.githubusercontent.com/28511788/56752169-afc03080-6755-11e9-80e5-02b43f76df7e.png">

No sabemos cual puede ser el error.

**Comment by arturokunder** [comment]
Antonia,
Que raro el error. 
Puedes hacer una prueba ahora?. Quizás está fallando una validación.
