### ISSUE TITLE
Preparacion Productos

### ISSUE THREAD

**Issue by vicentecastroa** [IIC3103/2019-proyecto#13]
En los productos, se puede ver una división entre "productos finales", "productos procesados" y "materias primas", o no? 
Es correcto asumir que un  "producto final" como un roll, solo va a necesitar "productos procesados", que a su vez se hace solo con "materias primas"??

Los sku de cada uno serian:
[1001, 1016] Materia Prima
[1101, 1407] Productos procesados
[10001, 30008] Productos finales

**Comment by arturokunder** [comment]
Vicente,
Si, los SKU son como tú dices.
Ojo que un "producto final" puede usar "productos procesados" y/o "materias primas".

**Comment by vicentecastroa** [comment]
Ok. Gracias
