### ISSUE TITLE
Dudas varias

### ISSUE THREAD

**Issue by dmolina2** [IIC3103/2019-proyecto#14]
Estimados tengo un par de dudas:

1) No me queda claro si nuestra API además de recibir pedidos por productos, además tiene que efectivamente llevar a cabo estos intercambios.

2) A partir del Lunes de la próxima semana, todos los grupos partirán de 0?, es decir, ahí es cuando tendremos que comenzar a fabricar nuestros productos (de los cuales nuestro grupo no posea restricciones) y luego mandar solicitudes a los otros grupos de productos que nos falten para completar el stock mínimo?

Muchas Gracias.

**Comment by arturokunder** [comment]
1. Por supuesto que si! Tienen que llevar a cabo los intercambios, de forma contraria, no podrán cumplir con el stock mínimo exigido.
2. Si, todos partirán de cero en el ambiente de producción
