### ISSUE TITLE
Fabricar producto sin pago

### ISSUE THREAD

**Issue by sdiez1** [IIC3103/2019-proyecto#15]
Al hacer el PUT, me muestra:
"error": "Lo sentimos, ha ocurrido un error grave."

Es por estar haciendo mal el PUT?

**Comment by elramirezv123** [comment]
Ami me pasa lo mismo :(

**Comment by gomara** [comment]
Hola
Me pasa lo mismo y me aparece 503 Service Unavailable

**Comment by arturokunder** [comment]
Cuando te muestra 
`"error": "Lo sentimos, ha ocurrido un error grave."`
Es porque está mal formateado el request.
Asegurate de tener el `body` en formato json y con el header `content-type:application/json`

**Comment by arturokunder** [comment]
Revisando en más profundidad, tengo que hiciste el request con el siguiente header:
```
Content-Type | multipart/form-data
```
Asegurate de estar enviando los datos con los headers y formatos correctos.
Según los logs del sistema, tengo este error por lo menos con los grupos 6, 10 y 11.

**Comment by sdiez1** [comment]
Muchas gracias!
