### ISSUE TITLE
Mover productos entre almacenes Http status 500

### ISSUE THREAD

**Issue by Zepk** [IIC3103/2019-proyecto#16]
Al realizar la request para mover productos entre almacenes, siempre obtenemos Http status 500.

Esto sucede independientemente de que parametros se envíen en la request, vale decir, aun si se usa una key diferente a la del grupo, en lugar de decir que el usuario no tiene autorizacion, se obtiene Http status 500

Asi es el mensaje de request original, que luego pasa por la funcion de hash
![image](https://user-images.githubusercontent.com/11397612/56778489-6c40e300-67a4-11e9-906e-e59cdc9af003.png)

![image](https://user-images.githubusercontent.com/11397612/56778737-dd34ca80-67a5-11e9-9c2d-064a64c1f0bd.png)

Y a este url estamos enviando la request
![image](https://user-images.githubusercontent.com/11397612/56778511-88dd1b00-67a4-11e9-9ef9-0766a5436c8c.png)

La id del almacen que entregamos en un almacen del grupo, y la id del producto corresponde efectivamente a un producto en otro de nuestros almacenes, ambas id se pasan como strings.

**Comment by arturokunder** [comment]
También tengo registrado que hubo un error por mi lado, pero el problema está en el request mismo, no en el servidor.
Si no me equivoco, es porque te falta el header `content-type: application/json`, y/o porque el body del request no lo estás enviando como jsonl

**Comment by arturokunder** [comment]
Cuéntame como te va

**Comment by Zepk** [comment]
Muchas gracais! Efectivamente se me habia olvidado pasar el body a json
