### ISSUE TITLE
Solicitud de plazo adicional

### ISSUE THREAD

**Issue by nivek0o0** [IIC3103/2019-proyecto#17]
Buenos días Profesor, 

como grupo queremos saber si existe la posibilidad de extender el plazo de la primera entrega, fundado en los siguientes motivos:

1. La publicación de los datos de Productos y la API Bodega funcionando estaban planificados para el 18, pero finalmente se subieron el 21. Esto nos quitó un importante fin de semana de trabajo y nos dejó con solo 1 semana para entender los datos, diseñar nuestra API y desarrollarla. Hay que tener en cuenta 

2. Entender los datos de Productos nos tomó un tiempo no despreciable, en especial por las equivalencias kilos y litros, la gran cantidad de columnas, entre otros.

3. El avance de mi grupo ha sido implementar hace poco una BD local donde guardar la información de productos, ingredientes, grupos productores y pedidos, además de diseñar la arquitectura. Ahora estamos entendiendo cómo usar trabajos asíncronos en Rails. Sé de otros grupos que llevan menos que eso.

4. Todos los servidores del DCC están caídos hasta nuevo avíso, por lo que no podemos avanzar en el deploy.

Gracias.

**Comment by Dalal15** [comment]
Hola!

Nuestro grupo (10) lleva un progreso parecido. Sumado a lo que dice Kevin, creo que sería bueno considerar que para lograr el stock mínimo se necesita de las materias primas de cada grupo. Dado esto, sería bueno tener más plazo para que todos logren hacer que la API funcione.

Muchas gracias.

Saludos.

**Comment by arturokunder** [comment]
Hola
Acabo de hacer pruebas y los servidores se encuentran activos nuevamente.
Respecto de la solicitud de plazo, les respondo mañana.

Arturo.

**Comment by NicolasAguirre** [comment]
@arturokunder puede ser q ahora este caido el servidor?? 
Por otro lado, sería ideal si pudieran correr la entrega. Muchas Gracias!

**Comment by nivek0o0** [comment]
Estuvo casi todo el día así, o devolviendo otros errores.
![Captura de pantalla de 2019-04-27 03-20-26](https://user-images.githubusercontent.com/20782451/56844161-6f6aca80-689b-11e9-8bc0-fae048ba8428.png)

**Comment by santiagocruzb** [comment]
![image](https://user-images.githubusercontent.com/13748925/56852156-73233f00-68e5-11e9-9a2c-c2912801451e.png)

Está complicado trabajar con esta velocidad de subida ah..

**Comment by nivek0o0** [comment]
![Captura de pantalla de 2019-04-27 19-19-39](https://user-images.githubusercontent.com/20782451/56854139-79371100-6921-11e9-9a6a-cb2cd149c0d8.png)

**Comment by farojos** [comment]
Si tienen problemas para la subida de archivos. Intenten usar github

**Comment by nivek0o0** [comment]
@farojos Hola, ¿cómo instalo gemas y hecho a correr el servidor desde github? 
Gracias
![error](https://user-images.githubusercontent.com/20782451/56854250-10509880-6923-11e9-9dc1-233b17c1c86a.jpg)

**Comment by farojos** [comment]
@nivek0o0 

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/7420935/56854262-c7d4b300-6901-11e9-81ce-98319b3df385.png">


Acabo de entrar sin problemas

**Comment by farojos** [comment]
> @farojos Hola, ¿cómo instalo gemas y hecho a correr nuestra app en el servidor del DCC desde github?
> Gracias
> ![error](https://user-images.githubusercontent.com/20782451/56854250-10509880-6923-11e9-9dc1-233b17c1c86a.jpg)

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/7420935/56854309-44679180-6902-11e9-9ddf-4d65700a7af8.png">


A lo que me refiero es que los servidores cuentan con git.

**Comment by farojos** [comment]
Estimados, 

El equipo docente ha decidido mover la entrega para el martes dado los problemas con los servidores.

El aviso oficial vendra via siding.

Ante otras dudas porfavor tratenlas en otro issue
