### ISSUE TITLE
Mover productos entre bodegas [Http status 400 - Bad Parameters]

### ISSUE THREAD

**Issue by dmolina2** [IIC3103/2019-proyecto#18]
Tengo una duda con respecto a los datos parámetros, ya que con mi grupo hemos tratado múltiples formas para probar esta request y no hemos logrado hacerla funcionar.

Primero que todo, se que el parámetro oc es opcional, pero si lo quiero poner ¿pongo cualquier string?, ya que es un ObjectId que rails lo lee como string. 

Segundo, cuando hago movimiento de productos entre almacenes ¿hay un tiempo de demora para que este producto, por ejemplo, vaya de la recepción al despacho?, ¿o el traspaso es inmediato?
¿Se aplica lo mismo para el movimiento entre bodegas?

Probé la request con un id_producto que tengo en mi despacho con la id_recepción de un grupo externo, oc = "random" y precio = 1.

Muchas Gracias

**Comment by arturokunder** [comment]
Hola!
Prueba ahora. 
Parece que la OC no sé estaba validando correctamente cómo opcional.

**Comment by dmolina2** [comment]
Ahora me esta tirando un error [Http status 401] - "Usuario no autorizado".

**Comment by farojos** [comment]
> Ahora me esta tirando un error [Http status 401] - "Usuario no autorizado".

Estimado, puedes mostrar tu request con un scr en postman

**Comment by dmolina2** [comment]
Arreglado!

Gracias
