### ISSUE TITLE
id de respuesta metodo fabricar

### ISSUE THREAD

**Issue by afcerna** [IIC3103/2019-proyecto#19]
Al momento de llamar al metodo fabricarSinPago para fabricar 10 unidades del prodcuto sku 1001 y este es exitoso, la respuesta es:

{
    "__v": 0,
    "created_at": "2019-04-25T20:49:38.531Z",
    "updated_at": "2019-04-25T20:49:38.531Z",
    "sku": "1001",
    "grupo": 12,
    "cantidad": 10,
    "_id": "5cc21d6255cd270004579e06",
    "disponible": "2019-04-26T00:26:07.330Z",
    "despachado": false
}

Según la documentación el "_id" es la id del producto, pero estas no eran unitarias? no deberían ser 10 "_id" para cada una de las instancias del producto pedido?

**Comment by arturokunder** [comment]
Tienes razón, debería decir "ID de la fabricación"
Los id de los productos los obtienes una vez que de ha ejecutado la fabricación a través del método obtener productos en almacén
