### ISSUE TITLE
Problemas servidor y plazo entrega

### ISSUE THREAD

**Issue by cjgazali** [IIC3103/2019-proyecto#20]
Hoy estuve mucho tiempo tratando de correr la aplicación en el servidor pero la conexión era intermitente y no hubo caso. No logré ejecutar 4 comandos de corrido que me permitieran dejarla andando; la conexión se cortaba antes de que termine. Además, todo se demora mucho, por ejemplo, he tenido que esperar mucho para hacer la conexión (comando ssh) y he tenido que esperar mucho cada vez que se interrumpe la conexión (se queda pegado hasta que me echa).

Entiendo que ahora la evaluación comienza el martes. Eso es el martes a las 00:00; tenemos que terminar el lunes, correcto?

Desde ya, considerando mi experiencia y los avances que tengo enterados de los grupos con los que he hablado, me gustaría proponer que la evaluación comience el miércoles. La velocidad ha sido muy lenta hasta el momento.

Si más gente está teniendo estos problemas, es bueno saber!
Gracias.

**Comment by bleon1** [comment]
Yo también tuve problemas con la conexión hoy.

**Comment by sggr94** [comment]
Yo estoy con problemas con la API, estoy tratando de hacer request a la url /fabrica/fabricarSinPago y recibo como respuesta Status 503.
No sé si será problema mió o a alguien más le ha pasado.

**Comment by farojos** [comment]
Estimados,

Probando actualmente, mí tiempo para hacer login ssh es de 2 segundos. Pueden mostrarme si tienen algún problema de red en este minuto. Agreguen tambien su número de grupo para ver si su maquina tiene algún problema. Tambien les recomiendo usar tmux.

De todas formas consideren que el hacer deploy es el proceso más rapido que debiese demorar bastante poco (un par de horas a lo mucho) asi que les recomiendo avanzar de forma local si no pueden por problemas de servidor.

Para ayudarlos, les dejare aca un archivo base con el cual se pueden basar para hacer deploy con docker para rails:

dockerfile
```
FROM ruby:2.3 #cambien al ruby que utilicen

# Install dependencies
RUN apt-get update -qq
RUN apt-get install -y build-essential libpq-dev nodejs

# Prepare app
RUN mkdir /app
WORKDIR /app
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
RUN bundle install
COPY . /app
ENV RAILS_ENV=production
ENV SECRET_KEY_BASE=RELLENEN ESTO :)
ENV POSTGRES_PASSWORD=ESTO TAMBIEN :) !!!
# Expose and setup start command
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
```

docker-compose

```
# docker-compose.yml
version: '2' #actualizar a la version 3
services:
  loadbalancer:
    image: dockercloud/haproxy #DEPRECADO, les reocmiendo cambiar por nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    links:
      - webapi
  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=RELLENE ESTO
      - POSTGRES_DB=ESTO TAMBIEN DEBEN CAMBIARLO
      - POSTGRES_PASSWORD=ESTO TAMBIEN
  webapi:
    build: .
    restart: always
    depends_on:
      - postgresql
    environment:
      - POSTGRES_PASSWORD=OJO CAMBIEN ESTO
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true|false ... depende de que quieren ver
```

**Comment by cjgazali** [comment]
Justamente el problema es que en más de dos horas no he podido hacer deploy!
Además, tuve otro problema, ver #22.

**Comment by farojos** [comment]
> Justamente el problema es que en más de dos horas no he podido hacer deploy!
> Además, tuve otro problema, ver #22. Gracias!

Solucionado

**Comment by cjgazali** [comment]
Gracias Felipe, te pasaste!
Resuelto el problema en #22 , de todos modos no insistiré con deploy ahora porque nuevamente la conexión es intermitente y entre un comando y otro me echa. Eso cae nuevamente en el tema de este issue.

**Comment by farojos** [comment]
> Gracias Felipe, te pasaste!
> Resuelto el problema en #22 , de todos modos no insistiré con deploy ahora porque nuevamente la conexión es intermitente y entre un comando y otro me echa. Eso cae nuevamente en el tema de este issue.

Tmux les permite abrir una consola en el servidor para que no pierdan sus avances si se desconectan (si se desconectan, la consola continua abierta)

**Comment by farojos** [comment]
Estimados,

La entrega queda oficialmente para este martes.

Saludos
