### ISSUE TITLE
/fabrica/fabricarSinPago respuesta Status 503.

### ISSUE THREAD

**Issue by farojos** [IIC3103/2019-proyecto#21]
Yo estoy con problemas con la API, estoy tratando de hacer request a la url /fabrica/fabricarSinPago y recibo como respuesta Status 503.
No sé si será problema mió o a alguien más le ha pasado.

_Originally posted by @sggr94 in https://github.com/IIC3103/2019-proyecto/issues/20#issuecomment-487330390_

**Comment by JoseRomeroi** [comment]
Me esta pasando lo mismo. Alguien más?

**Comment by farojos** [comment]
Para dejar claro sus problemas, publiquen la request que les falla usando postman y mostrando el header + body si es que corresponde

**Comment by arturokunder** [comment]
El 503 da cuando hay algún error en el servidor (generalmente dado por algunos requests mal formados) y debe reiniciarse.
Según mis estadísticas, la api ha presentando un uptime de 100% en las últimas 24 horas 
![image](https://user-images.githubusercontent.com/3254309/56874923-48330b00-6a0b-11e9-833c-f31fe2d86033.png)

Arturo.
