### ISSUE TITLE
Error con docker-compose down

### ISSUE THREAD

**Issue by cjgazali** [IIC3103/2019-proyecto#22]
Finalmente pude llegar a docker-compose up (en #20 comento lo difícil que fue). Luego de up quedó corriendo en terminal. Abrí otra ventana de terminar, me conecté con ssh también, y traté de hacer docker-compose down, pero me arroja error.

<img width="774" alt="Captura de pantalla 2019-04-27 a la(s) 21 11 01" src="https://user-images.githubusercontent.com/20786646/56856827-6c221e00-6931-11e9-95d9-90ebde5238d4.png">

No encontré soluciones en internet.
Probé soluciones como ésta:
https://parekhparthesh.blogspot.com/2016/08/docker-unable-to-remove-network-has.html
Pero no las pude completar sin errores.

En este momento tengo una ventana con el docker-compose up corriendo y no me atrevo a cerrarla.

Ayuda! Siempre nos han dicho que es grave no hacer docker-compose down bien.
Duda: en el peor de los casos, ¿cuál es la mejor escapatoria? (Por decir algo, algúna forma de resetar docker, y/o borrar carpeta y volver a clonar desde git. (Cloné mi repo git en el servidor, y tengo cero problema con borrar todo y volver a clonar.)

Gracias!

**Comment by farojos** [comment]
@cjgazali 

Me metere en el servidor para ver que sucede

**Comment by farojos** [comment]
Efectivamente algo raro sucedio, procedere a limpiar todas las instancias de docker

**Comment by farojos** [comment]
Como levantaste los servicios, al parecer es un daemon con algo un poco mas complejo

**Comment by farojos** [comment]
La mejor forma de ayudarte es que me entregues el tutorial con el cual dejaste andando el daemon

**Comment by farojos** [comment]
Estimado @cjgazali 

Hice limpieza completa de docker y ya puedes volver a trabajar.

Te recomiendo que uses el parametro -d de docker compose para que quede detach, o en su defecto usar tmux

Saludos
