### ISSUE TITLE
Trabajo en proyecto durante clase lunes

### ISSUE THREAD

**Issue by cjgazali** [IIC3103/2019-proyecto#23]
Sería espectacular tener tiempo mañana para trabajar en el proyecto, para poder vernos las caras y ayudarnos entre todos. Esto podría reducir drásticamente los errores y el tiempo en arreglarlos, por ejemplo, en el tema de las APIs entre grupos. Creo que a muchos grupos, quizás todos, nos ayudaría mucho.

¿Será posible?
Muchas gracias!

**Comment by farojos** [comment]
Dato / Trick: 

Si bien estaremos midiendo durante 3 días, quizas un continuous deployment los puede ayudar a ponerse al dia si estan en plena evaluación. Bajo su propio riesgo obviamente (se suele acompañar con CI para minimizar esos riesgos)

Saludos
