### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by acrojas2** [IIC3103/2019-proyecto#24]
Hola:
Con mi grupo queremos usar docker. Luego de varios intentos, logramos levantar los contenedores. Prueba de eso se puede ver acá:
<img width="762" alt="Captura de pantalla 2019-04-29 a la(s) 00 29 50" src="https://user-images.githubusercontent.com/26121354/56876529-0bb8dc80-6a16-11e9-9a1b-48d4e93807a4.png">
Luego, voy al local en el puerto 3000 y me tira error, en la consola me aparece lo siguiente:
<img width="932" alt="Captura de pantalla 2019-04-29 a la(s) 00 52 09" src="https://user-images.githubusercontent.com/26121354/56876992-19239600-6a19-11e9-8521-b32cbb5a1e65.png">
He googleado  y no se como arreglar el error. Ayuda!
De antemano gracias, 
Saludos.

**Comment by acrojas2** [comment]
Por si ayuda a que me puedan ayudar, el contenido del dockerfile es este:
<img width="406" alt="Captura de pantalla 2019-04-29 a la(s) 00 54 24" src="https://user-images.githubusercontent.com/26121354/56877058-6f90d480-6a19-11e9-9003-1a2a981dd105.png">
y el del docker-compose.yml este
<img width="435" alt="Captura de pantalla 2019-04-29 a la(s) 00 54 16" src="https://user-images.githubusercontent.com/26121354/56877065-79b2d300-6a19-11e9-98d4-8cc9c1baec86.png">
Eso! Saludos

**Comment by farojos** [comment]
postgres esta sin usuario sin db y sin clave

**Comment by farojos** [comment]
miren el ejemplo de la issue #20

**Comment by arturokunder** [comment]
Ojo también con los puertos
La entrada al servidor es a través del puerto 80, no 3000.
[Documentación Docker sobre los puertos](https://docs.docker.com/compose/compose-file/#ports)
