### ISSUE TITLE
Funcionamiento Hook

### ISSUE THREAD

**Issue by dalliende** [IIC3103/2019-proyecto#26]
Los Hooks estarán funcionando para esta entrega?. Lo otro, si seteo un Hook, me llegara una request por cada por cada producto a la url indicada? o será por cada pedido?. 

Hay alguna forma de pasarle algun parametro a este hook?

Edit: El parametro _id de fabricar sin pagar, es el id del primer producto que llegara? y este _id si o si es de un producto del lote? 

gracias

**Comment by arturokunder** [comment]
1. Los hooks no están funcionando
1. El _id de fabricar sin pagar es el _id del envío de fabricación
