### ISSUE TITLE
GET a APIs grupos

### ISSUE THREAD

**Issue by cjgazali** [IIC3103/2019-proyecto#27]
Prints que puse para revisar GET a grupos hace un rato.
fail: no funcionó request
KeyError: no viene con llaves "sku" y/o "total"

fail 1
fail 2
fail 3
fail 4
fail 5
fail 6
KeyError 7
fail 8
9 OK (no tenía productos)
fail 10
11 OK
fail 12
(fail 13) nosotros
14 OK

Solo para dejar constancia de la situación a docentes y para recordarnos que es importantísimo responder exactamente a las urls que definimos y con las estructuras que definimos, exactamente. No olviden revisar la documentación que generamos.

**Comment by cjgazali** [comment]
(Grupo 13 ya estamos arriba! Deberíamos responderles a todo...)

**Comment by jtagle2** [comment]
Yo soy del grupo 7.
Efectivamente nosotros teníamos un error en las keys, estabamos enviando cantidad y no total, pero lo solucionamos hace un par de horas (antes de las 10).
Lo puedes corroborar en http://tuerca7.ing.puc.cl/inventories

Los pedidos también los tenemos implementados, hicimos varias pruebas enviando a otros grupos y no hubo problemas. (Hacemos camarones por si te sirve)

Saludos
