### ISSUE TITLE
POST a APIs grupos.

### ISSUE THREAD

**Issue by cjgazali** [IIC3103/2019-proyecto#29]
Similar a #27, pero recién ejecutado:

fail 1
fail 2
fail 3
fail 4
fail 5
fail 6
fail 7
fail 8
KeyError 9
KeyError 10
fail 11
fail 12
fail 14

**Comment by arturokunder** [comment]
Cristóbal,
Para el monitoreo, revisa el issue #31

**Comment by jtagle2** [comment]
Nuevamente, soy del grupo 7. Después de la hora que pusiste (tipo 17:00 debe haber sido) nuestra api debería haber estado funcionando.
Como no habían otros grupos para probar, lo probamos en consola con el comando
`curl --header "Content-Type: application/json"  --header "group:X" --request POST   --data '{"sku":"1006","cantidad":50,"almacenId": "IDDETUALMACEN"}'   tuerca7.ing.puc.cl/orders -v`
y andaba bien (en desarrollo le enviamos productos a varios grupos).
Si te sigue fallando me avisas

Utilizando ese mismo formato para enviarles a ustedes, me tira un error de índice. Dice
>IndexError at /orders
>list index out of range

El error específico lo arroja en
> File "/code/app/subtasks.py" in move_product_client 
>183.         mover_entre_bodegas(lista_productos[i]['_id'], id_almacen_destino)

Saludos

**Comment by JoseRomeroi** [comment]
Cristobal no puedo pedirte palta

**Comment by nivek0o0** [comment]
¿Cuál es la idea de llorar porque otros grupos no tienen implementadas las órdenes si ustedes tampoco lo tienen bien hecho?
Se están haciendo los locos con los pedidos, no están despachando lo que aceptan...

**Nuestro inventario antes**
![Captura de pantalla de 2019-05-01 14-08-36](https://user-images.githubusercontent.com/20782451/57021014-a41fae80-6c1a-11e9-9693-ea3b17a14b41.png)


**La orden**
![Captura de pantalla de 2019-05-01 14-10-29](https://user-images.githubusercontent.com/20782451/57021123-e648f000-6c1a-11e9-9f49-4345d5724ebf.png)

**Nuestro inventario a los 10 minutos**
![Captura de pantalla de 2019-05-01 14-20-38](https://user-images.githubusercontent.com/20782451/57021647-599f3180-6c1c-11e9-997d-291715e47823.png)

**Comment by nivek0o0** [comment]
Index error....
![Captura de pantalla de 2019-05-01 15-38-05](https://user-images.githubusercontent.com/20782451/57025627-39c13b00-6c27-11e9-83fa-d1fb2a526077.png)

**Comment by cjgazali** [comment]
@nivek0o0, por favor, no hables así, es para ayudarnos entre todos de buena fe.
Vamos a mirar lo que dicen.

**Comment by nivek0o0** [comment]
A mi no me pareció de buena onda ni de solidaridad entre los grupos intentar asegurarse con el: _para dejar constancia de la situación a docentes_, que interpreté como _nosotros estamos listos pero los otros grupos no_

**Comment by cjgazali** [comment]
Me disculpo, era para cubrirnos a todos. No sabíamos cómo se monitorea, y si estamos todos abajo, quizás a los docentes les interesa. Nosotros no estábamos listos. La otra opción es que fuera error nuestro que nos fallaran las conexiones! Es solo para que salgan temas y promover comunicación. Si quieres hablamos en persona el lunes. Saludos!
