### ISSUE TITLE
Dudas sobre pedidos

### ISSUE THREAD

**Issue by Dalal15** [IIC3103/2019-proyecto#3]
Hola! Tenemos la duda de si más adelante existirán restricciones de tiempo en la realización de pedidos. ¿Por ahora asumimos que los pedidos son instantáneos? ¿Es por esto que no se pueden modificar o eliminar?

Muchas gracias!

**Comment by arturokunder** [comment]
A que te refieres con realización de pedidos?
- Si es a los movimientos entre distintos almacenes/bodegas, si, siempre es instantáneo y no va a cambiar
- Si te refieres a la fabricación de productos, no, no es instantánea. En el momento de fabricación, la fábrica te dirá la hora estimada de envío de los productos
