### ISSUE TITLE
Revisar si task (job) ejecuta en servidor

### ISSUE THREAD

**Issue by cjgazali** [IIC3103/2019-proyecto#30]
¿Alguna recomendación de cómo podemos saber, durante los días siguientes, que un task (Django + Celery) está ejecutándose en servidor como se espera?

task de Django + Celery entiendo que equivale a los jobs de Rails, para los cuales la duda quizás es la misma.

Duda por el lado de los logs, lo hablamos en clase el lunes pero en la práctica no conocemos cómo hacer o revisar logs para, por ejemplo, esta entrega!

**Comment by arturokunder** [comment]
Deja un log!
Los logs quedan en un archivo que tu definas.
En la (documentación de Django)[https://docs.djangoproject.com/en/2.2/topics/logging/] se habla extensamente de esto (incluso con ejemplos!)
