### ISSUE TITLE
Monitoreo Entrega

### ISSUE THREAD

**Issue by arturokunder** [IIC3103/2019-proyecto#31]
Estimados,
Pueden seguir el monitoreo de la entrega a través en los siguientes lugares:

- Monitoreo servicios: [Link Dashboard](https://stats.uptimerobot.com/ZzJBJH0pp)
- Monitoreo stock mínimo:
  - [Estadísticas de Stock en Desarrollo](https://docs.google.com/spreadsheets/d/1-IDFPM4KVP9rukq8RDTn8bk4npQ2VSB9EGM5fm-MM9I/edit#gid=2028713689)
  - [Estadísticas de Stock en Producción](https://docs.google.com/spreadsheets/d/1z-ndf53cMwIVnYvrmBXIJxQYrL9i2OLn17rILhOkAS0/edit#gid=2028713689)

**Comment by arturokunder** [comment]
PD: El dashboard de monitoreo de servicios no valida el formato de la respuesta del servicio.

**Comment by cjgazali** [comment]
No supe si hacer una issue aparte, me dicen si es mejor, pero en Estadísticas de Stock en Producción somos tres grupos que tenemos unos #VALUE en la planilla. No sé cómo interpretarlo... ¿qué podría ser?

**Comment by JoseRomeroi** [comment]
@arturokunder profesor qué significan exactamente los porcentajes? Nuestro grupo tiene más de 300 masagos, pero no aparece 100%. saludos

**Comment by jtagle2** [comment]
@JoseRomeroi, por lo que yo tengo entendido, debe ser como un promedio de nivel de stock (si vez la fórmula de las celdas, es un promedio de datos desde que se empezó el monitoreo a la fecha). 
Me imagino que el sistema nos mide los stocks cada cierto tiempo, y luego el valor que nos muestra ahí es el promedio de todos los niveles que ha monitoreado hasta el momento.

**Comment by arturokunder** [comment]
@JoseRomeroi Es como dice @jtagle2 .
Se calcula el promedio de los promedios por hora del stock de cada sku.
De todas formas, revisaré las fórmulas para ver que esté todo en orden
