### ISSUE TITLE
Consulta cantidad de sésamo para sésamo tostado

### ISSUE THREAD

**Issue by timellado** [IIC3103/2019-proyecto#32]
Hola!
Tengo una duda con el ingrediente sésamo para el producto sésamo tostado, donde en el docs aparece como que un lote de 2 unidades de sésamo tostado se fabrica con 1.1 unidades de sésamo. La api de mi grupo trató de hacer la fabricación de 4 sésamos tostados, donde movimos 3 unidades de sésamo a despacho (2.2 aproximado hacia arriba), pero nos entregó un error de que esperaba 4 unidades de sésamo en despacho. Mi pregunta es si estamos calculando mal la cantidad nosotros o hay algún problema con las cantidades en bodega. 
Saludos

**Comment by arturokunder** [comment]
Tomás,
2 unidades de sésamo producen un lote de sésamo tostado, donde un lote de sésamo tostado equivale a 2 un.
Por lo tanto, para obtener 4 unidades de sésamo tostado, debes dejar en despacho 4 unidades de sésamo.
Como expliqué en clases, en el documento, lo importante son las columnas que dicen "unidades bodega", las que son las equivalentes a cuantas unidades en bodega se deben mover para las cantidades requeridas.
En el caso del sésamo:

![image](https://user-images.githubusercontent.com/3254309/57040402-4ba5dc80-6c2d-11e9-8d9b-f83c3a6c3de0.png)
