### ISSUE TITLE
Uso de Redis

### ISSUE THREAD

**Issue by norman123123** [IIC3103/2019-proyecto#33]
Estamos usando workers con sidekiq y la documentación indica que es necesario usar redis.
En este caso quiero utilizar un archivo de configuración config/initializers/sidekiq.rb para correr los workers al inicial el servido y para esto la documentación me pide el url del servidor redis.
En el archivo tiene que ir lo que sale aca: 

[Using Redis](https://github.com/mperham/sidekiq/wiki/Using-Redis)

Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://redis.example.com:7372/0' }
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://redis.example.com:7372/0' }
end

Pero no se que poner en url o como saber que va ahí o como conseguir ese valor. Nos podrían ayudar con eso? Es necesario instalar redis en el servidor tambien, lo que no estoy seguro como hacer.

**Comment by arturokunder** [comment]
Si te entiendo bien, quieres levantar Redis en el servidor del curso, por lo tanto, la url sería la del mismo servidor, en este caso, `redis://tuerca4.ing.puc.cl:7372/0`

Ahora, tendrás un problema ya que el puerto `7372` no está abierto por lo que no podrás acceder a esa url. 

Sin embargo, como en este caso, tu servidor Rails está alojado en la misma máquina que tu BD Redis, puedes acceder a este mediante una url `localhost`, quedándote la url como `redis://localhost:7372/0`, o equivalentemente, `redis://127.0.0.1:7372/0`.

**Comment by farojos** [comment]
Te recomiendo usarlo con docker + docker-compose.

docker-compose es capas de generar una subred dentro del pc con ciertas facilidades: asi como localhost -> 127.0.0.1 docker-compose genera alias de este estilo: por ejemplo si tienes postgres y llamas asi a tu servicio: al usar como host: postgres este apuntara (lo mas probable) a 127.0.0.1:5432. Este mismo principio es extrapolable para redis en uso con rails. Hay buenos tutoriales al respecto.

De no haberlo resuelto aun, pueden intentar con este tutorial:

https://nickjanetakis.com/blog/dockerize-a-rails-5-postgres-redis-sidekiq-action-cable-app-with-docker-compose
