### ISSUE TITLE
Velocidad despacho entre grupos

### ISSUE THREAD

**Issue by jtagle2** [IIC3103/2019-proyecto#34]
Tengo una duda. ¿El despacho entre los grupos siempre es instantáneo? (cuando al que le piden manda el despacho, ¿le llega altiro al que lo pidió?)
Que un grupo me mandó paltas, me llegaron a la bodega pulmón, pero cuando pido los SKU con stock de dicha bodega no me aparecen las paltas que me mandaron.
¿A alguien más le pasa?

**Comment by Dalal15** [comment]
Al grupo 13 que tiene paltas, nos dimos cuenta que para que llegaran los pedidos había que pedir de cantidades pequeñas. 
@jtagle2, tu grupo tiene camarón cierto? No hemos podido realizar un pedido exitoso a tu grupo. ¿Lo hicieron de otra manera?

**Comment by jtagle2** [comment]
@Dalal15 lo hicimos como dice la API. ¿Qué error te tira?

Respecto a las paltas, el pedido que hice fue de poco, y me llego despachado en `true`. De hecho, es muy raro, porque ahora hay productos flotando en alguna parte parece.

![image](https://user-images.githubusercontent.com/6934080/57054183-ec61bf80-6c60-11e9-947b-3d63a262a7a2.png)
Ahi me dice que tengo 4653 productos en la bodega, pero al pedir el skusWithStock de ese almacen, me tira que en total hay 4641. Y si hay algo que estoy entendiendo mal, igual al pedir las paltas me aumentaba el stock pero no me las daba en el skusWithStock. Muy raro

**Comment by arturokunder** [comment]
@jtagle2 
Acabo de revisar tus pedidos de palta en la información que tengo yo.
Tuviste 415 paltas en tu bodega, pero ya están vencidas.

```json
{
    "_id": {
        "$oid": "5cca31deda568e0004ef9502"
    },
    "grupo": 7,
    "almacen": {
        "$oid": "5cc7b139a823b10004d8e6f5"
    },
    "sku": "1010",
    "vencimiento": {
        "$date": "2019-05-01T03:19:00.066Z"
    },
    "oc": null,
    "direccion": "",
    "precio": 0,
    "despachado": false,
    "costo": 0,
    "__v": 0
}
```

Respecto de los espacios en las bodegas, skusWithStock tiene información más precisa que el `usedSpace` de los almacenes, que a veces se desincroniza.

**Comment by Dalal15** [comment]
@jtagle2 arroja status 500.

**Comment by jtagle2** [comment]
@arturokunder, ¿Y no puede ser que se estén enviando productos vencidos? Porque me acaban de aceptar 2 pedidos de 10, me aumentó el usedSpace, pero nuevamente no veo mis paltas :(

**Comment by jtagle2** [comment]
Podría apostar mis 415 paltas vencidas, a que mi proveedor de paltas tiene una base de datos en su servidor, y para enviar los productos los saca de su base de datos local y por ende manda ids de productos vencidos 🤔
