### ISSUE TITLE
Tiempo de producción 

### ISSUE THREAD

**Issue by Dalal15** [IIC3103/2019-proyecto#35]
Hola!

¿Habrá algún error en el tiempo de producción de los productos? Por ejemplo, el arroz cocido debería producirse en 40 minutos. El pedido lo realizamos aproximadamente a las 10:40 y aún no nos aparece en nuestro inventario.

Notamos que la hora que entrega la Api de bodega es incorrecta, pero no sabemos si eso influye:

![WhatsApp Image 2019-05-02 at 11 55 22 AM](https://user-images.githubusercontent.com/20782505/57090284-7bf48600-6cd4-11e9-821c-964d655a04ac.jpeg)

Saludos!

**Comment by Zepk** [comment]
A mi tambien me da la impresion de que efectivamente algunos productos que no son materias primas tienen tiempos de produccion que son mas largos de lo que figura en el excel.

**Comment by arturokunder** [comment]
Efectivamente se produjo un cuello de botella en la fábrica.
Básicamente, 
```
tasa de llegada > tasa de procesamiento
```
Aumenté la capacidad para producir más pedidos por hora, además de procesar los que estaban pendientes.
