### ISSUE TITLE
Almacen despacho lleno?

### ISSUE THREAD

**Issue by Zepk** [IIC3103/2019-proyecto#36]
Me pasa que, cuando hago botener almacenes, me aparece que mi almacen de despacho esta lleno:
`"totalSpace":87,"usedSpace":87"`.

Pero al hacer el request de los materiales dentro de la bodega, estos no debiesen usar todo el espacio:
`[{"_id":"1003","total":3},{"_id":"1001","total":8},{"_id":"1004","total":2},{"_id":"1002","total":3},{"_id":"1016","total":2}]`.

Otras veces incluso sucede que la bodega figura como llena, sin embargo, al pedir los productos que se encuentran en ella, figura como vacia. Esto evita que se puedan enviar a fabricar nuevos productos, o despachar a otros grupos (ya que la bodega de despacho figura como llena). Sin embargo, tampoco es posible vaciar la bodega (ya que no tiene productos en ella)

Por que sucede esto, es comportamiento normal?
Existe un delay en vaciar la bodega al mover productos fuera de esta?

**Comment by arturokunder** [comment]
Si, existe un delay en la actualización de los espacios utilizados, que pasa porque los productos vencidos no "desaparacen" del conteo inmediatamente y a veces, se produce un desfase temporal por temas de concurrencia.

**Comment by arturokunder** [comment]
pd: Los materiales en bodega que obtienes a través de `getSkusWithStock` es el stock real y actualizado
