### ISSUE TITLE
Borrar productos 

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC3103/2019-proyecto#37]
Alguien sabe como poder borrar productos. Tuvimos un error y producimos sobrestock

**Comment by arturokunder** [comment]
Usa el método [Despachar stock](https://integracion-2019-dev.herokuapp.com/bodega/docs/#api-Bodega-DeleteStock).
En OC, usa cualquier ObjectId con formato válido (puedes usar alguno de los que están en la misma documentación) y los productos empezarán a "desaparecer" de la bodega.

**Comment by matnagra** [comment]
Que dirección hay que poner?

**Comment by arturokunder** [comment]
Un string cualquiera
