### ISSUE TITLE
DUDA GENERAL TODOS

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC3103/2019-proyecto#39]
Al hacer un get y post hay algunos grupos que lo tienen con / al final y otros que no. cual es la metodologia que se usa envdad??

**Comment by NicolasAguirre** [comment]
Por otro lado, hay algunos grupos que estan tirando 201 en vez de 200 pueder ser?

**Comment by cjgazali** [comment]
Django por defecto espera slash al final o lo pone solo, podría ser eso, pero nuestro grupo configuró Django para q sea sin slash, xq en la documentación de todos los pusimos sin slash.

201 Created es correcto para el POST.
