### ISSUE TITLE
Dudas de enunciado y términos

### ISSUE THREAD

**Issue by cjgazali** [IIC3103/2019-proyecto#4]
En el enunciado, Trabajo a realizar:

1.a. ¿Qué define exactamente a un stock disponible para la venta? En otras palabras, ¿en qué almacenes de la bodega los productos se consideran disponibles para la venta? Entre recepción, cocina, despacho y pulmón.

1.b. ¿Qué desencadena la recepción de un pedido en esta entrega? Considerando que no usaremos orden de compra `oc`. ¿Debemos tener una base de datos para guardar pedidos? ¿Algo más?

2. Dice 'Realizar pedidos a materias primas' pero entiendo que usaremos Fabricar productos Sin Pago, lo que implica que no necesitamos materias primas. Además, no usaremos el hook, me pregunto si eso significa que en esta entrega no trabajaremos con materias primas, si no solo con los productos terminados, fabricados Sin Pago. // Además, dice 'procesar alimentos'; ¿a qué se refiere? Si no tenemos materias primas, significaría usar Fabricar productos Sin Pago, ¿correcto?

En la documentación parecieran mezclarse los 'productos' con las 'materias primas' y las 'bodegas' con los 'almacenes' de una bodega. Esto genera muchas dudas y sería bueno ser estrictos en los términos.

- En esta entrega, tendremos productos asignados para Fabricar productos Sin Pago, y no tendremos asignadas materias primas pues no las recibiremos en esta entrega, ¿correcto?
- A otro grupo, ¿puedo pedirle productos y materias primas, o solo productos?

Muchísimas gracias.

**Comment by arturokunder** [comment]
Cristóbal,

1. El stock disponible para venta es la suma del stock "vigente" en toda la bodega del grupo, o sea, en cualquier almacén.
El stock vigente es aquel que no está vencido ni usado para algún despacho (vendido).

2. En esta entrega no recibirán órdenes de compra. Sólo deben poder mantener el stock.

3. La fabricación tiene los siguientes inputs: pago de la fabricación, y materias primas a procesar, en caso de requerirse. Si por ejemplo, quieres producir salmón ahumado, debes pasar como materia prima salmón crudo. El "sin pago" se refiere a que en esta entrega la fabricación no tendrá costo.

4. En la bodega, un "producto" es equivalente a una "materia prima". El producto es el producto final que tu buscarás vender (en este caso, los sushis), y las materias primas, los ingredientes o insumos para fabricarlos. El tratamiento en los sistemas es exactamente igual para cada uno. No hay ninguna diferencia.
Entre los grupos se pueden enviar todo tipo de productos que esté en su bodega.

5. Para recibir materias primas, en esta entrega, basta con mandarlas a fabricar. Si no las tienes asignadas, tendrás que pedírselas a otro grupo.

**Comment by cjgazali** [comment]
Muchas gracias. Respecto a su respuesta:

2. Pero sí se evalúa realización de pedidos entre grupos. No entiendo qué se ejecuta cuando se recibe un pedido, 'qué hay que hacer' cuando se recibe un pedido. ¿Estamos 'obligados' a responder inmediatamente rebajando lo que nos pidieron, si está disponible para la venta? ¿Cómo rebajar? ¿Cómo aumentar, si yo soy el que hizo el pedido?

3. Entonces la duda que me queda es de la documentación; ¿a qué se refiere 'fabricar productos con o sin materias primas'? Hay productos que son materias primas y los obtendremos al pedirlos si nos son asignados o al pedírselos a otro grupo, y hay productos que usarán materias primas para fabricarse y los obtendremos al pedir su fabricación, lo cual rebaja las materias primas correspondientes, ¿correcto?

- Me surgió a continuación otra duda: ¿cómo sabremos los lotes y proporciones para fabricar cada producto? Sería bueno tenerlos, o no es necesario?

Muchísimas gracias.

**Comment by arturokunder** [comment]
Cristóbal,

2. No estás "obligado" a aceptar el pedido. Los pedidos los puedes aceptar o rechazar, y enviar cuando tu decidas
3. 
    - *Hay productos que son materias primas y los obtendremos al pedirlos si nos son asignados o al pedírselos a otro grupo*  **CORRECTO**. Estos productos también se obtienen al llamar al método de fabricación.
    - *hay productos que usarán materias primas para fabricarse y los obtendremos al pedir su fabricación, lo cual rebaja las materias primas correspondientes* **CORRECTO**
4. Los entregaremos el 18/04, junto con la asignación de productos.
