### ISSUE TITLE
Mover productos al Pulmon

### ISSUE THREAD

**Issue by dalliende** [IIC3103/2019-proyecto#40]
Hay alguna opción de enviar productos al pulmon? me hace sentido de que si es una bodega externa nosotros podamos enviar voluntariamente productos a esta. De poderse cual es la forma de hacerlo? y si no se puede se podria implementar? al final es un costo extra que asume el equipo que quiera ocupar este metodo.

**Comment by farojos** [comment]
Si no me equivoco, se mueve igual a como se usa el resto de movimientos entre almacenes.

@arturokunder porfavor confirmar

**Comment by arturokunder** [comment]
No, no puedes enviar productos al almacén pulmón.
Podríamos cambiar esa restricción, pero por ahora está de esa forma.

**Comment by dalliende** [comment]
Se habilitara esta funcionalidad para esta entrega? y se modificaran las capacidades de los almacenes?

Saludos

**Comment by arturokunder** [comment]
@dalliende se habilitó que los productos se puedan enviar a pulmón, siempre y cuando el producto se encuentre en el almacén de despacho para el envío.

Respecto del tamaño de los almacenes, si se modificarán las capacidades (se aumentarán)
