### ISSUE TITLE
Para todos: Inventario y oc

### ISSUE THREAD

**Issue by dalliende** [IIC3103/2019-proyecto#41]
Creo que para esta entrega es necesario mostrar en el inventario solo los productos disponibles, para que no tengamos problemas de generación de ordenes de compra innecesarias, que van a resultar rechazadas y terminaran bajando la nota de todos.

Por otro lado propongo que como grupos utilicemos la sugerencia del profesor de agregar el id de la oc en la misma petición entre grupos que hemos utilizado para la entrega anterior.

![entrega2](https://user-images.githubusercontent.com/11409081/57530495-5c2d1580-7305-11e9-8c1c-1b0a0367d026.png)

**Comment by Dalal15** [comment]
Con mi grupo estamos de acuerdo en hacer eso. ¿No les parece hacer un grupo en whatsapp para ponernos de acuerdo más rápido? La idea que sea uno por grupo. Mi número +56 962871510.
 
Saludos!

**Comment by martinalvarado4** [comment]
Sobre lo primero que dices tengo una duda, según los puntos de evaluación no existe criterio sobre "Aceptación mínima de compras B2B" solo de cumplimiento una vez ya aceptada la orden. 
@arturokunder queda entonces a criterio de cada grupo si rechaza muchas ordenes de compra de otros grupos???

**Comment by cjgazali** [comment]
Bancamos whatsapp con uno por grupo!
+569 7558 6633
Somos el grupo 13.
