### ISSUE TITLE
Servidores FTP

### ISSUE THREAD

**Issue by sdiez1** [IIC3103/2019-proyecto#42]
Hay algún problema con el ambiente de desarrollo en los servidores ftp?
Me puedo conectar solo al de producción.

Saludos

**Comment by arturokunder** [comment]
No, no debería haber ningún problema.
Me acabo de conectar con tus credenciales y me funcionó correctamente

**Comment by Zepk** [comment]
Yo tampoco me  puedo conectar al servidor de desarrollo, solo al de produccion. Pareciera como que la password que me dieron no es la correcta
