### ISSUE TITLE
Servidores FTP en realidad son SFTP?

### ISSUE THREAD

**Issue by silvamatias** [IIC3103/2019-proyecto#43]
Hola, 

Tratando de conectarme a los servidores FTP desde nuestra app no era posible y desde FileZila si. FileZila usaba SFTP por defecto y cuando lo obligaba a conectarse al servidor como FTP me tiraba el siguiente error:

<img width="494" alt="Screen Shot 2019-05-14 at 4 54 40 PM" src="https://user-images.githubusercontent.com/13739643/57731565-edcfb680-7668-11e9-9f89-f6aa996df63a.png">

Por lo que asumo que los servidores están seteados como SFTP y no FTP. Esto cambiaría la forma de conectarse, alguien podría confirmar esto? ya que ninguna parte de la entrega leí que debíamos usar el protocolo SFTP.

gracias

**Comment by arturokunder** [comment]
Matías,
Si.

Las conexiones son SFTP. El puerto 22 está reservado para conexiones cifradas por SSH o SFTP.
El puerto para FTP tradicional por lo general es por el puerto 21, y hoy se usa poco debido a que no es muy seguro.
