### ISSUE TITLE
Conocer tiempo de producción de productos finales

### ISSUE THREAD

**Issue by cafuentes1** [IIC3103/2019-proyecto#44]
Para aceptar o rechazar un pedido debemos conocer el tiempo en el que tendremos los productos finales disponibles, pero este tiempo se retorna solo después de mandar a fabricar. Por lo tanto, tendríamos que rechazar los pedidos después de mandarlos a producir, y esa producción se perdería. ¿Hay una forma de conocer este tiempo antes de mandar a producir?

**Comment by arturokunder** [comment]
Estimado,
En el documento está el tiempo esperado de producción, el cual, para los productos finales, varía entre 10 y 30 minutos.
Con ese tiempo, +/- un delta, puedes calcular si alcanzas o no.
