### ISSUE TITLE
Duda API oc

### ISSUE THREAD

**Issue by atbusch** [IIC3103/2019-proyecto#45]
He estado tratando de hacer la request para crear una oc y no me ha funcionado. No me queda claro como se entregan los parámetros, traté con body y me entrega Response [404] y si lo hago sin entregar parámetros me entrega Response [500]: 'Lo sentimos, ha ocurrido un error grave.', además de que en ese caso no estaría entregando los parámetros y en todas las consultas de las oc está así. Cual es la manera correcta de hacerlo?

**Comment by farojos** [comment]
> He estado tratando de hacer la request para crear una oc y no me ha funcionado. No me queda claro como se entregan los parámetros, traté con body y me entrega Response [404] y si lo hago sin entregar parámetros me entrega Response [500]: 'Lo sentimos, ha ocurrido un error grave.', además de que en ese caso no estaría entregando los parámetros y en todas las consultas de las oc está así. Cual es la manera correcta de hacerlo?

Estimado @atbusch

Puedes adjuntar la request hecha con Postman, con el header, body, method y url para poder replicar el error.

Saludos

**Comment by arturokunder** [comment]
@atbusch 
Dejo un screenshot de request de ejemplo:
![image](https://user-images.githubusercontent.com/3254309/57977601-fc500200-79c9-11e9-9db1-d388d3ff4e27.png)


Si sigues teniendo problema, adjunta el request como solicita @farojos

**Comment by atbusch** [comment]
Ya había solucionado el problema, se me olvidó decirlo. Gracias a los dos por la ayuda!

**Comment by santiagocruzb** [comment]
Hay inconsistencias entre la documentación y el screenshot. El `sku` aca es string, pero en la doc es int. Intenté igual de las 2 formas y no soluciono (obtengo error de `400 Bad Request`).

Mis parametros son
```json
{  
   "cliente":"5cbd31b7c445af0004739bed",
   "proveedor":"5cbd31b7c445af0004739be3",
   "sku":"1010",
   "fechaEntrega":1558739568270,
   "cantidad":10,
   "precioUnitario":200,
   "canal":"b2b",
   "notas":"notas",
   "urlNotificacion":"emol.com"
}
```
Alguna idea?
