### ISSUE TITLE
Aplicacion Caida 

### ISSUE THREAD

**Issue by Zepk** [IIC3103/2019-proyecto#46]
Tanto el sistema de bodegas como el de ordenes de compra se encuentran caidos, por lo que no se puede acceder a la documentacion ni realizar ningun tipo de request

![image](https://user-images.githubusercontent.com/11397612/57975901-b2532600-79a1-11e9-8c81-448800a0a695.png)

**Comment by arturokunder** [comment]
@Zepk efectivamente estuvo caída a ratos por un problema en un procesamiento.
Avísame si se vuelve a caer.
