### ISSUE TITLE
Problema Acceso a servidores FTP

### ISSUE THREAD

**Issue by Zepk** [IIC3103/2019-proyecto#47]
Ya se hizo una issue al respecto, pero se encuentre cerrada, asi que decidí hacer otra por si la anterior no se vuelve a revisar. 

Al igual que en #42 no me es posible acceder al servidor FTP de desarollo, y unicamente puedo acceder al de produccion. Siempre que ingreso la constraseña que me dieron, me la vuelve a pedir, como si la constraseña fuese incorrecta.

Ademas de mi grupo y el de la issue #42 se que hay al menos 1 grupo mas que tampoco puede conectarse al servidor de desarrollo

**Comment by arturokunder** [comment]
Hola!
Resetié las claves a ver si ahora les funciona.
Probé por mi lado y me pude conectar sin problemas

**Comment by Zepk** [comment]
Ahora si funciona!
