### ISSUE TITLE
Notificación URL

### ISSUE THREAD

**Issue by Dalal15** [IIC3103/2019-proyecto#48]
Hola,

En la documentación de la API OC se señala que al crear una OC el parámetro "urlNotificacion" es opcional, ¿No debería ser obligatorio? Si no se manda este parámetro, ¿Cómo se realizaría el Post de ejemplo que sale en el enunciado?

En cuanto al ejemplo del enunciado, ¿Ese Post lo realiza la API OC o el grupo vendedor directamente? 

Gracias!

**Comment by arturokunder** [comment]
El post lo realiza el grupo que recibe la OC, por eso no es obligatorio el parámetro.
Lo pueden usar como un medio adicional de comunicación entre los grupos, o seguir usando lo que ya venían usando de la entrega anterior.
