### ISSUE TITLE
[Aclaración] Método Mover producto entre bodegas

### ISSUE THREAD

**Issue by arturokunder** [IIC3103/2019-proyecto#5]
El método **Mover producto entre bodegas** solicita los siguientes parámetros:

Campo | Tipo | Descripción
-- | -- | --
productoId | ObjectId | Id de producto a despachar.
almacenId | ObjectId | Id de almacén de destino.
oc | ObjectId | Id de orden de compra asociada al despacho.
precio | Number | Precio al que fue vendido el producto. Debe ser mayor a 0.

Consideren para la entrega 1, el campo OC como opcional.
No usaremos órdenes de compra en esta entrega.
Se actualizará la documetanción de acuerdo a lo anterior para reflejar esto.

**Ojo**
En esta entrega NO deben usar el método "Despachar producto", ya que este "envía" el producto hacia el cliente final y no a una bodega de otro grupo.

**Comment by cjgazali** [comment]
Nos sorprende el `productId`. Si no es un sku y es un id de producto, entonces, estamos diciendo a dónde queremos mover una única unidad de producto, de algún sku que nos hayan pedido, ¿correcto?
¿No debería ser un sku? ¿Cuántas unidades puede mover este Método?

**Comment by arturokunder** [comment]
Por que te sorprende?
Efectivamente, el movimiento es unitario. Como dije anteriormente, el productId representa la instancia física de un producto.
Esto es muy común en sistemas de gestión de inventario. El tener sólo un "stock total" genera varios problemas. Por ejemplo, como podrías controlar que todos los productos pueden tener fechas de vencimiento distintas, u otro caso típico de la agricultura, como controlas toda la cadena logística de un producto? Desde de que planta se obtuvo la fruta, hasta que pesticidas le fueron aplicado, pasando por quién fue el que la recogió, cuando, etc.

Por lo tanto, respondiendo a la pregunta, sólo puedes mover de un ítem a la vez.

**Comment by seba608** [comment]
Profesor,

Qué parámetros recibirá este método? En particular, qué hacemos con los parámetros 'oc' y 'precio'. Hemos estado intentando pero nos arroja el error de parámetros incorrectos.

**Comment by arturokunder** [comment]
El parámetro oc no es validado por el servicio, por lo que puedes enviarlo vacío, con cualquier valor, o no enviarlo.
Respecto del precio, ahora no tiene relevancia pero debe ir un valor válido.
Avísame si tienes algún problema.
