### ISSUE TITLE
Problemas fabricar y espacio recepción

### ISSUE THREAD

**Issue by AlainLotissier** [IIC3103/2019-proyecto#51]
Al fabricar sin pago, la consulta me retorna como resultado que la orden fue creada con éxito.
<img width="367" alt="Captura de Pantalla 2019-05-23 a la(s) 16 51 14" src="https://user-images.githubusercontent.com/13738904/58285686-4135b900-7d7b-11e9-9239-8ec42aa59d93.png">
Sin embargo no está sacando los ingredientes necesario desde la bodega de despacho por lo que la bodega se llena de ingredientes que se encuentran "usados" y que no puedo sacar con otros métodos. ¿Este funcionamiento es normal? Ayer los sacaba prácticamente al instante.

Adicionalmente a este problema, no sé cómo, pero logramos tener más productos en la bodega de recepción que la capacidad máxima permitida. 
<img width="340" alt="Captura de Pantalla 2019-05-23 a la(s) 16 57 10" src="https://user-images.githubusercontent.com/13738904/58285996-d3d65800-7d7b-11e9-896f-59d2f726b1e0.png">
Esto no significa un problema para nosotros, pero quería dejar constancia de ese comportamiento.

**Comment by arturokunder** [comment]
Alain,
Estás seguro que los productos no están saliendo al fabricar?
Según mis registros, por cada orden de producción de 4 unidades de sku 1114 (cebollín cortado para roll), ha salido una unidad de sku 1014 (cebollín entero) de tu bodega.
En particular, para la orden que pones, se utilizo el producto `id` `5ce5d00af7b4a60004b7d9d7` para la fabricación. 
Donde sí puede haber un problema, es en el atributo `usedSpace` de los almacenes, el cual a veces tiene problemas de concurrencia y se demora en actualizarse al valor real.

Esto genera los problemas del segundo punto que planteas. Es por eso que a veces puedes tener más elementos en un almacén que su capacidad, ya que al hacer el cálculo, se agregan elementos siendo que no había capacidad.
Como tu dices, esto no les afecta, por lo que no deberías tener problema.

Si necesitas obtener los stocks reales en un punto, puedes usar el método `getSkusWithStock`

**Comment by AlainLotissier** [comment]
Efectivamente, al rato de una hora aproximadamente terminaron saliendo de despacho. Gracias por la explicación, no nos había ocurrido antes.

**Comment by AlainLotissier** [comment]
Sin embargo esto me genera otra duda. Dado que fabricar sin pago no saca los productos de inmediato (no sé cuánto se está demorando actualmente pero por lo menos más de 30 minutos),  los métodos que tenemos definidos para fabricar ingredientes a partir de materias primas se caen debido a que se llena el almacén de despacho. 

Mi pregunta es si este comportamiento es algo de lo que tenemos que hacernos cargo o es un problema que está teniendo el servidor? Porque antes del martes las materias primas salían inmediatamente y este error no se generaba.

**Comment by arturokunder** [comment]
@AlainLotissier 
Los productos salen inmediatamente. Si bien, el parámetro `usedSpace` puede a veces demorar en actualizarse, el producto no lo puedes volver a usar o mover porque ya esta "consumido" (estado `despachado` en la bodega).

En desarrollo puedes tener este problema, pero en producción el problema se genera mucho menos y "recupera" el estado mucho más rápido (el servidor de prod tiene más recursos que el de dev).

**Comment by arturokunder** [comment]
Espero que haya quedado más claro.
Cualquier cosa me escribes!

**Comment by AlainLotissier** [comment]
Perfecto. Muchas gracias por la respuesta!
