### ISSUE TITLE
Carpeta pedidos SFTP

### ISSUE THREAD

**Issue by Tibrahm** [IIC3103/2019-proyecto#52]
Recorriendo los diferentes archivos XML de la carpeta pedidos me aparece que los archivos se encuentran vacíos, es esto correcto?

**Comment by arturokunder** [comment]
@Tibrahm que archivos estás viendo?
Revisé los últimos 6 correspondientes a tu grupo y todos me aparecen con el contenido correcto.

![image](https://user-images.githubusercontent.com/3254309/58342541-aa223d00-7e1e-11e9-8555-bf090e6bc7e4.png)

**Comment by Tibrahm** [comment]
ya logre solucionarlo ! Gracias !
