### ISSUE TITLE
SKUs pedidos por FTP

### ISSUE THREAD

**Issue by augustoal** [IIC3103/2019-proyecto#53]
Nos dimos cuenta que los SKUs que salen en los archivos FTP no coinciden con los de la orden de compra respectiva (si uno busca la orden de compra a través de la API). Cual es el que debemos usar? El de la orden de compra?

**Comment by arturokunder** [comment]
@augustoal Tienes toda la razón.
Ya corregí el error, ahora los xml estarán correctos. De todas formas, lo que vale, siempre es la información que da la API
