### ISSUE TITLE
Problema entendiendo casilla sftp

### ISSUE THREAD

**Issue by nicoparraguez** [IIC3103/2019-proyecto#55]
Hola, tengo varias dudas acerca del funcionamiento del buzón y los archivos xml.
1. el id de los archivos se refiere al id de  orden de compra de ese pedido o es solo un id del archivo?

2. en el caso que leo el archivo xml y envió o adquiero la orden de compra debo borrar ese archivo del buzón por que o sino de forma asincrona voy a cada vez llamar los mismos archivos xml

de antemano , muchas gracias.

**Comment by arturokunder** [comment]
Hola,
1. No te entendí muy bien, pero si con id de archivo te refieres al nombre, ese nombre es un id único con el único fin de que no se repitan los nombres de archivos. No tiene ninguna relación con el id de la orden de compra. El id de la OC lo puedes obtener en el contenido xml del archivo.
2. No se pueden borrar los archivos. En la casilla, sólo tienen permiso de lectura sobre los archivos.
