### ISSUE TITLE
Lógica de revisión de servidor FTP

### ISSUE THREAD

**Issue by cjgazali** [IIC3103/2019-proyecto#56]
¿Alguna idea de cómo es mejor buscar por OCs nuevas en servidor?
¿Los archivos .xml solo se acumulan y nunca se borran?

Una política que acorta la búsqueda es borrar archivo de OC cada vez que rechazamos o que aceptamos, pero no estamos seguros de si esto es correcto.

De momento nos estamos demorando más de 2 min en revisar archivos actuales. Si sumamos consumir API OC y tomar acciones, está demorando mucho.

Gracias!

**Comment by nicoparraguez** [comment]
Yo tengo exactamente la misma duda

**Comment by arturokunder** [comment]
@cjgazali @nicoparraguez acabo de responder en el issue #55 
No necesitan ir a buscar los archivos que ya leyeron. Esos archivos no cambiarán. Basta con que sólo revisen los nuevos archivos que hay en la casilla desde la última vez que consultaron
