### ISSUE TITLE
Consulta atributo oc producto

### ISSUE THREAD

**Issue by seba608** [IIC3103/2019-proyecto#58]
Hola,

Revisando la API de bodega, el método Obtener productos almacén devuelve una lista de productos, los cuales tienen un atributo oc, que puede ser null. Mi pregunta es, ¿cómo lo hace el sistema para ver que oc tiene un producto en el almacen? Hago esta pregunta porque al momento de mandar a fabricar no se requiere el parámetro oc y lo necesitamos para usar el método Despachar producto.

Saludos,
Sebastián

**Comment by arturokunder** [comment]
El parámetro `oc` lo asignas cuando despachas el producto final, con el método [`DELETE /stock`](https://integracion-2019-dev.herokuapp.com/bodega/docs/#api-Bodega-DeleteStock).
Ojo ahí con la asignación de la `oc` correcta, ya que esto es clave para la obtención posterior de las estadísticas de despacho.
