### ISSUE TITLE
Duda Ingrediente Camarón

### ISSUE THREAD

**Issue by svergara1** [IIC3103/2019-proyecto#59]
Hola,

Para producir un lote de Camarón Cocido (sku: 1106), se necesita 100 de Camarón en despacho, sin embargo el totalSpace de la bodega de despacho es de 79. Hay un error en los datos?

Gracias

**Comment by tomvillage** [comment]
camarón que se duerme...

**Comment by arturokunder** [comment]
Como se conversó en alguna de las clases, se aumentaron los espacios de todos los almacenes para que puedan tener más capacidad para todos los productos.

Acabo de hacer este cambio en desarrollo y producción

**Comment by dalliende** [comment]
En todo caso 100 unidades de camarón ocupan 1 unidad de bodega.  Mientras que 1 unidad de camarón cocido ocupa 1 espacio de bodega. Asi que independientemente del espacio debería alcanzarte.

**Comment by arturokunder** [comment]
Gracias @dalliende por la aclaración. Me parecía raro que no dieran los espacios porque me preocup´é bastante en la entrega anterior que no se dieran situaciones como esa, pero no lo revisé en profundidad.
