### ISSUE TITLE
Ciclo de vida de pedido

### ISSUE THREAD

**Issue by cjgazali** [IIC3103/2019-proyecto#6]
Hablando con otros grupos creo que no entendemos el ciclo de vida de un pedido. Pensando en el enunciado, API expone 1.a. Recibir pedidos de productos.

- ¿Qué es un pedido?
- ¿Un pedido puede ser de varios productos o es un pedido por cada producto que queramos?
- Al recibir un producto, ¿qué hago, 'inmediatamente' (respuesta de la API para 1.a.)?
- ¿Cuándo 'muere' un pedido? ¿Necesitamos tenerlos en una base de datos? ¿Para esta entrega 1?

Muchas gracias!

**Comment by arturokunder** [comment]
Cristóbal:
Un pedido es una solicitud de ciertos productos de un grupo A a un grupo B, o de un "cliente final" a un grupo.
Grupo B (receptor del pedido) puede aceptarlo o rechazarlo.  
Si es de un producto o varios productos lo deciden ustedes. Los pedidos de "clientes finales" llegarán como mix de varios productos y cantidades, por si quieren homologar los pedidos entre grupos con los usuarios finales.
Lo que haces "inmediatamente" es lo que tienen que definir para esta entrega.
El pedido "muere" o termina cuando: a) es rechazado por grupo B, o b) en el caso de ser aceptado, cuando se entregan todos los productos solicitados por el grupo A.
