### ISSUE TITLE
Fecha Entrega (Plazo)

### ISSUE THREAD

**Issue by NicolasAguirre** [IIC3103/2019-proyecto#60]
Estimado profesor: 
Sería util si pudiera dar un poco mas de plazo, con mi grupo estamos un poco atrasado por la cantidad de cosas q hemos tenido (capstone en especialidad, las fechas de entrega calzan con los finales de ciclo de este ultimo). Esto mismo hace que retrasemos a los otros grupos a testear funcionalidades y se genera una reacción en cadena haciendo que ningun grupo pueda probar sus funcionalidades hasta el mismo día de la entrega (o sea mña). Yo se que dieron harto tiempo, pero al final todos trabajan a último minuto por lo mismo de que si alguein empezo hace harto igual tiene que esperar al resto para testear que su api funcione en el sistema. 

Por otro lado, estamos re complicados porque no podemos cocinar nada (necesitamos sal y no tenemos sal para el arroz y la otra opcion era probar con salmon ,  pero tmpco producimos). 
 Gracias, espero su respuesta

**Comment by arturokunder** [comment]
Estimados,
Según lo conversado hoy en clases, las órdenes en producción comenzarán a llegar tipo 10pm de mañana.

Pueden realizar un seguimiento de como van en el portal de estadísticas:
- [DEV](https://integracion-2019-dev.herokuapp.com/estadisticas/oc)
- [PROD](https://integracion-2019-prod.herokuapp.com/estadisticas/oc)
