### ISSUE TITLE
Consulta datos tipo fecha

### ISSUE THREAD

**Issue by seba608** [IIC3103/2019-proyecto#61]
Hola,

Cuando creo una orden de compra, el atributo created_at que devuelve la consulta es cuatro horas mayor que la hora real. Por ejemplo, si creo una orden a las 19 horas, el atributo created_at tiene la hora en 23, por ende, para crear una orden de compra tengo que poner una fecha de entrega mayor a 23 horas o no me deja crearla. ¿Está bien eso?

Saludos

**Comment by arturokunder** [comment]
Estimado,
Las fechas están en horario UTC. Como Chile está +4 en este momento, entonces las 11am en Chile serían las 3pm horario UTC.

**Comment by nivek0o0** [comment]
Profesor, ¿por qué la documentación dice que las fechas tienen formato POSIX pero cuando obtengo la información de una **oc** el atributo `created_at` es del tipo _"2019-05-26T00:10:53.160Z"_?
