### ISSUE TITLE
"Sku no encontrado"

### ISSUE THREAD

**Issue by smanriquez96** [IIC3103/2019-proyecto#62]
Revisando métodos anteriores me topé con que productos que debo producir, soy el grupo 1, me arrojan {"error"=>"sku no encontrado"}. Los sku que pregunto en la imagen, si los debo producir, es decir, grupo 1 debe producir "1002" y "1005".Ademas, estos no necesitan materias primas para ser producidos, Por otro lado, si pido "1001", si me acepta fabricar.
![Captura de pantalla de 2019-05-26 21-25-04](https://user-images.githubusercontent.com/26236067/58389984-d09dcf00-7ffc-11e9-9e38-6cb07f16666c.png)

**Comment by arturokunder** [comment]
Desarrollo o producción? Aun no actualizo los productos en el segundo, por lo que te debería decir `no encontrado` si en la entrega 1 no los producías.
Haré el cambio en un rato.

**Comment by smanriquez96** [comment]
En producción me responde eso.

**Comment by arturokunder** [comment]
Hiciste alguna prueba después de las 10pm?
Ya debería estar funcionando correctamente
