### ISSUE TITLE
Duda cuando realizar la recepcion de las OC 

### ISSUE THREAD

**Issue by dmolina2** [IIC3103/2019-proyecto#63]
Profesor,

Me dijo en clases que dejara por escrito mi duda que hice en clases. Esta correspondía a que si era necesario realizar la recepción de una oc recibida (b2b) *antes* que comience a realizar el movimiento del productos entre bodegas o realidad no importaba si se hacía esta después o que ni siquiera se hiciera.

Muchas Gracias!

**Comment by arturokunder** [comment]
Hola,
Gracias por recordarme. Estas son las reglas de negocio asociadas a los estados de las OC's

1. Para realizar movimientos entre bodegas o despachos, basta con que envíes el parámetro `OC`. Esto asignará que tu producto fue enviado para cumplir el despacho de la OC mencionada.
1. Para realizar el despacho indicando la OC, no importa en que estado está la oc.
1. Para que la OC cuente como cantidad despachada, debe estar en estado `aceptada`. Si la OC no está en ese estado, no se contabilizará correctamente el envío realizado.
1. `cantidadDespachada` sólo se actualizará si los despachos fueron realizados antes de la fecha de entrega requerida (tiene un pequeño delta para evitar casos borde).
1. El estado `finalizada` (oc completada), se asigna automáticamente una vez que la cantidad despachada es mayor o igual a la cantidad requerida.

**Comment by arturokunder** [comment]
pd: esto aplica para todas las oc, tipo `ftp` o `b2b`

**Comment by dalliende** [comment]
Yo sigo teniendo una duda. Para despachar correctamente un producto es necesario solo hacer la llamada DELETE /stocks y agregar la oc. O es necesario hacer esta llamada y ademas /movestock?

**Comment by arturokunder** [comment]
Para despachar una `oc` de tipo ftp, debes hacerlo con [DELETE /stock](https://integracion-2019-dev.herokuapp.com/bodega/docs/#api-Bodega-DeleteStock)
Si es para un despacho entre grupos, debes usar [Mover producto entre bodegas](https://integracion-2019-dev.herokuapp.com/bodega/docs/#api-Bodega-PostMovestockbodega)

**Comment by dalliende** [comment]
Pero como identifica el sistema que los productos que se mueven entre grupos pertenecen a una oc especifica?
