### ISSUE TITLE
Monitoreo

### ISSUE THREAD

**Issue by jtagle2** [IIC3103/2019-proyecto#64]
Respecto al monitoreo de las ordenes de compra. El porcentaje de cumplimiento de las ordenes de compra B2B considerará solo las ordenes de compra que fueron creadas desde el comienzo del monitoreo? (10pm de hoy).

**Comment by arturokunder** [comment]
Si, hasta ahora no hay órdenes creadas en el ambiente de producción

**Comment by elramirezv123** [comment]
@arturokunder Profe una duda, he estado pidiendo varias veces del sku "1109" (pedí ayer en la noche y hoy en la mañana 9 am) y aún no ha llegado nada. Habrá algún problema con ese? Porque solo nos pasa con ese sku en particular.

**Comment by arturokunder** [comment]
A mi me aparece como `despachado`
la fecha de entrega es el parámetro `disponible`.
Según lo que me entregas, el producto debiese haber sido entregado el 28-5 a las 0:43 (ojo que todas las fechas que te da el sistema están en UTC).
Según mis registros, esa orden fue entregada el 28-5 a las 0:30, casi 15 mins antes de lo esperado.

En este momento, no tengo ninguna orden de sku 1109 a tu grupo no despachada.

**Comment by elramirezv123** [comment]
Mirando con detención la respuesta, el id del almacén que aparece ahí es `5cecb52d2062ec00045b9c1e` y el que me aparece al hacer `GET` de los almacenes es `5cc7b139a823b10004d8e6fd`, al parecer lo está enviando al despacho de development. Acabo de hacer un nuevo request y me sigue apareciendo lo mismo.

**Comment by elramirezv123** [comment]
Jajaja no dije nada, me confundí de ID. Pero igual es extraño, porque estoy ocupando la misma función para pedir a mano y el 1109 es el único que no llega :(

**Comment by arturokunder** [comment]
jaja no te preocupes. El `_id`  `5cecb52d2062ec00045b9c1e` corresponde a la orden de fabricación..no a un almacén. 

Del producto, me aparece que has producido 672 unidades de sku 1109. Sin embargo, ya se encuentran todas vencidas, ya que la vida esperada de ese producto (atún cortado para roll) es de 1,5 hrs.
El último que se despachó de la fábrica, se "fabricó" a las 13:35 UTC, los cuales vencieron a las 14:58 UTC.
Ahora tienes varias ordenes pendientes de producción.

**Comment by elramirezv123** [comment]
Todo calza ahora jajajaj Gracias! y perdón por el malentendido 😅
