### ISSUE TITLE
¿Reset?

### ISSUE THREAD

**Issue by acrojas2** [IIC3103/2019-proyecto#65]
Prodesor:
@arturokunder parece ser que no hizo el reset de producción a las 22:00 hrs. 
Saludos!.

**Comment by jtagle2** [comment]
Según el enunciado, se iba a hacer un reset de producción el 26 de mayo y no el día del comienzo del monitoreo.

**Comment by silvamatias** [comment]
De lo posible sería bueno que las métricas partieran un día después de lo acordado, ya que a muchos grupos no se les puede pedir

**Comment by jtagle2** [comment]
Creo que a su grupo no se le puede pedir. Trato y me tira error.

**Comment by silvamatias** [comment]
Pediste un sku que no es nuestro. Porfa si puedes testear con uno nuestro para darnos feedback :)

**Comment by jtagle2** [comment]
Probé pidiendo 2 de 1006 y me tiró el mismo error. (Me devuelve error 500 con la típica imagen de rails de something went wrong)

**Comment by arturokunder** [comment]
@acrojas2 no se porque no se mandó el mensaje ayer en la noche, pero es como dice @jtagle2  
No se iba a hacer ningún reset desde el domingo....

![image](https://user-images.githubusercontent.com/3254309/58529258-c831c980-819f-11e9-9767-4e8a4770c163.png)
