### ISSUE TITLE
Casilla FTP prod

### ISSUE THREAD

**Issue by FelipeApablaza** [IIC3103/2019-proyecto#67]
Según el monitoreo ya estamos recibiendo pedidos por el canal ftp (prod), pero con mi grupo no los podemos ver en la casilla usando filezilla 😕  

-

**Comment by Dalal15** [comment]
Hola, a nosotros nos pasa lo mismo (grupo 10).

**Comment by vbarros2** [comment]
Mismo problema (grupo 11). Tenemos 16 pedidos según estadísticas pero nada en la casilla

**Comment by jtagle2** [comment]
En el enunciado dice que hay máximo 5 minutos para responder las OCs, quizás después de ese tiempo borran las OC del servidor 🤔

**Comment by arturokunder** [comment]
No, las oc's nunca se borran.
Revisaré de inmediato

**Comment by arturokunder** [comment]
Hola,
Acabo de revisar.

Efectivamente, **para los grupos 10, 11 y 12,** las carpetas estaban mal creadas 😱 
Error mío.

Ya corregí y deberían comenzar a llegarles órdenes dentro de un rato.
Eliminaré aquellas ordenes creadas con anterioridad para que no les afecte, ya que no tenían como obtenerlas.

Arturo.

**Comment by vbarros2** [comment]
Se creo una nueva carpeta pedidos, pero sigue sin tener nada, ni pedidos11 ni pedidos

**Comment by FelipeApablaza** [comment]
Ojala exista una compensación por este error, pues estuvimos hasta por lo menos las 4 am, hora en que hice esta issue, debuggeando pensando que era un error nuestro, con la aplicación abajo fuera sin producir.
