### ISSUE TITLE
Tiempo Cocina

### ISSUE THREAD

**Issue by Tibrahm** [IIC3103/2019-proyecto#69]
Hace poco más de 1 hora envie a cocinar un pedido de 2 sku 10013, el cual tienen un periodo de producción de 10 minutos, y me llegaron luego de 1 hora. Además de esto solo me llego 1 de los 2 enviados, eso que fueron enviado a producir al mismo tiempo y ya  van 10 minutos de diferencia !

**Comment by arturokunder** [comment]
Que extraño. Ahora no hay nada "en cola" y se están procesando muchas más órdenes en fábrica que anteriormente.
Tienes el id del envío a fabricar para verificar?
