### ISSUE TITLE
Necesidad y uso de base de datos

### ISSUE THREAD

**Issue by cjgazali** [IIC3103/2019-proyecto#7]
Dado todo lo que abarca la API docente, no estamos seguros:

- ¿Necesitamos una base de datos? ¿Para esta entrega?
- De toda la lógica, ¿qué cosas deberíamos controlar en nuestra propia base de datos?

Las dudas de base de datos se relacionan también con #6.

Muchas gracias!

**Comment by arturokunder** [comment]
Usar o no BD lo deciden ustedes. 
Como tip, para esta entrega, los sistemas provistos no proporcionan ningún control de los pedidos recibidos o enviados.
