### ISSUE TITLE
Problemas Despacho producto ftp

### ISSUE THREAD

**Issue by fjsalinas** [IIC3103/2019-proyecto#70]
Estamos teniendo problemas con los despachos de ftp, mandamos a cocinar perfectamente lo que nos están pidiendo, luego me llegan a cocina y cuando los despacho me sale que fue despachado correctamente... pero nunca se actualizan las oc finalizadas en las estadísticas.
Esto me responde la API cuando hago el despacho:
![image](https://user-images.githubusercontent.com/8507323/58603418-b19e7780-825e-11e9-821e-613167365b50.png)
Alguien sabe que puede ser?? 
Muchas Gracias.

**Comment by arturokunder** [comment]
@fjsalinas me podrías enviar el id de la oc en cuestión?
Ojo que el estado "finalizada" se setea con un desfase, no en línea.

**Comment by fjsalinas** [comment]
Hola, son varios, pero aca le escribo un par que tengo anotados:

5ceec903fa598a00049e516b, 5cef05acc294640004dd2e85

Muchas Gracias.

**Comment by arturokunder** [comment]
@fjsalinas creo que ya se cual es el problema
La oc `5ceec903fa598a00049e516b` tiene como fecha de despacho `2019-05-29T19:31:00.000Z` (hora utc)
Pero los despachos de los 4 productos se realizaron a las `2019-05-30T01:53:05.658Z`, más de 6 horas después.
Si bien hay cierto margen de error, si la entrega se produce mucho más tarde de lo solicitado, la oc no se considera como finalizada.

**Comment by arturokunder** [comment]
pd: la oc `5cef05acc294640004dd2e85` no existe. Estás seguro que es el id correcto?
