### ISSUE TITLE
Almacen de despacho colapsado

### ISSUE THREAD

**Issue by seba608** [IIC3103/2019-proyecto#72]
Hola,

Del grupo 13 estamos teniendo problemas porque nuestro almacen de despacho está lleno hace mucho tiempo no sabemos por qué. O sea, cuando preguntamos a la API no siempre sale lleno y las respuestas cambian de un segundo a otro y mucho, pero el tema es que no nos deja mover nada a despacho. ¿Cómo podemos vaciarlo? Intentamos mover desde almacen despacho a pulmón, la respuesta es positiva por parte de la API pero no pasa nada en cuanto al espacio utilizado. Nosotros cada vez que mandamos a despacho, lo usamos para producir por tanto no debería estar tan lleno despacho. 

Saludos

**Comment by jtagle2** [comment]
Nosotros tuvimos un problema similar, y era que no se podían mover productos al pulmon. Lo movimos a otra de las bodegas (que no son ni despacho, ni cocina ni pulmón) y nos funcionó

**Comment by Zepk** [comment]
Agregando a lo que dice Joaquín, tambien hay problemas cuando los productos se vencen, al parecer cuando eso sucede, la actualizacion demora, se mencionó en la issue #36

**Comment by seba608** [comment]
Muchas gracias a ambos!
