### ISSUE TITLE
Demora de 2 horas para cocinar

### ISSUE THREAD

**Issue by fjsalinas** [IIC3103/2019-proyecto#74]
Nadie esta teniendo mucha demora pa cocinar hoydia?? Antes se me demoraba unos 10 minutos en cocinar y hoydia se me empezaron a demorar más de 2 horas! Y con tanta demora no estoy alcanzando a llegar a tiempo a para finalizar el pedido.
Saludos.

**Comment by Tibrahm** [comment]
#69

**Comment by dmolina2** [comment]
Me esta pasando lo mismo, no hemos podido finalizar los pedidos....

**Comment by seba608** [comment]
Lo mismo por aca...

**Comment by Nicolasvegam** [comment]
Same :(

**Comment by santiagocruzb** [comment]
Idem

**Comment by djnoguera** [comment]
lo mismo...

**Comment by Zepk** [comment]
+1

**Comment by joaquincastillo** [comment]
me pasa lo mismo

**Comment by dmolina2** [comment]
Estimado Profesor,
En clases me dijo que le escribiera en esta issue, para que revise bien el tiempo en que se cayó la base de datos de su API. Como puede ver, mi compañero de grupo @fjsalinas hizo esta issue el Viernes 31 de Mayo a las 9:54AM. El problema lo registramos la madrugada del viernes (5AM) de este mismo día pensando que era un problema nuestro, pero después nos dimos cuenta que era que los productos finales no llegaban.
Por este motivo, espero que pueda considerar la caida de la BBDD desde la madrugada del Viernes y no desde el Sábado que fue como había considerado, ya que fue desde el Viernes en la madrugada que ningún grupo pudo completar más órdenes de FTP.

Muchas Gracias!

**Comment by arturokunder** [comment]
@dmolina2 
Por favor ver #85
