### ISSUE TITLE
Comando para resetear

### ISSUE THREAD

**Issue by dalliende** [IIC3103/2019-proyecto#75]
Profesor:

Con mi grupo queríamos saber si existe la posibilidad de eliminar todos los productos y documentos del entorno de desarrollo (Ojala alguna nueva request). Esto porque tenemos muchos productos y con el rate de request que tenemos nos tomaría mucho tiempo y queremos probar nuestro código lo antes posible. 

Saludos,
Diego

**Comment by arturokunder** [comment]
Diego, el otro día resetié el ambiente de desarrollo para que puedan trabajar sin problemas, además de que tengan la capacidad de producir cualquier producto.
No puede hacer ese comando porque por la cantidad de elementos en la bd, sería lento e inestable.
