### ISSUE TITLE
Espacio en servidor

### ISSUE THREAD

**Issue by vicentecastroa** [IIC3103/2019-proyecto#76]
Hola, 
Estoy teniendo problemas con el deploy al servidor. Me dice que no me queda espacio disponible, pero no me hace sentido, ya que, según lo que entiendo, cada servidor tiene 20GB de disco duro. Cómo podría verificar eso y cómo saber qué es lo que me está llenando el disco?

Gracias!

**Comment by farojos** [comment]
Estimado @vicentecastroa ,

Si estas usando docker: 

Es normal que docker genere multiples contenedores basura si están haciendo demasiados cambios y ademas usan docker. Para solucionar puedes borrar todo manualmente, o usar el comando 

``` docker system prune ```

Si no estas usando docker: mándame un correo para coordinar una solución

**Comment by farojos** [comment]
Estimado @vicentecastroa,

La solución ya fue implementada.

Saludos
