### ISSUE TITLE
Exceso de FTP en carpeta

### ISSUE THREAD

**Issue by vbarros2** [IIC3103/2019-proyecto#77]
[Grupo 11]
Actualmente tenemos 170 ftp recibidos en las estadísticas, pero 1029 en la carpeta de ftp. 
Esto es un problema porque la mayoría de los id no tienen nada cuando llamo a la función obtener de la API y se demora mucho en llamar a los 1029.

Muchas gracias,

Vicente

**Comment by FelipeApablaza** [comment]
Yo remuevo los pedidos ftp ya vencidos manualmente (filezilla), y así evito ese problema. No se si hay otra forma.

**Comment by vbarros2** [comment]
Si es valido no tengo problema... Eliminas los rechazados y finalizados o solo los que no están validos? @FelipeApablaza

**Comment by vbarros2** [comment]
Ahora se eliminaron todos
