### ISSUE TITLE
Profe, se esta cayendo la API!

### ISSUE THREAD

**Issue by smanriquez96** [IIC3103/2019-proyecto#78]
![Captura de pantalla de 2019-06-19 16-07-46](https://user-images.githubusercontent.com/26236067/59796927-87b00200-92ac-11e9-8ac7-c69fc8da03c9.png)

**Comment by arturokunder** [comment]
No creo que sea la api. Ese error tiene más pinta de ser un error de la red donde estás conectado, ya que el error es que no se puede establecer conexión con la API.
Si la API estuviera fallando te daría un error 500 o 404.

Referencia:
https://stackoverflow.com/questions/3035226/getaddrinfo-temporary-failure-in-name-resolution-in-ror-application
