### ISSUE TITLE
Consulta conteo de productos despachados

### ISSUE THREAD

**Issue by seba608** [IIC3103/2019-proyecto#79]
Hola!

Junto a mi grupo nos surgió una consulta. Si un grupo nos realiza una orden de compra, debemos aceptarla antes de comenzar a despachar productos o si usamos mover producto entre bodegas con el id de la orden de compra cuenta igual en la cantidad despachada pese a que aún no se haya aceptado la orden?

Es decir, si primero aseguramos haber despachado todo y luego aceptamos la orden, queda finalizada la orden de compra?
 
Saludos

**Comment by arturokunder** [comment]
@seba608 no importa mucho el flujo, si aceptas la orden y despues despachas o si despachas y después aceptas.
Lo importante es que la aceptes ante que venza la fecha de despacho, ya que de forma contraria, la OC no quedará como finalizada.
