### ISSUE TITLE
PROBLEMAS para cocinar

### ISSUE THREAD

**Issue by afcerna** [IIC3103/2019-proyecto#80]
Al tratar de cocinar el producto con sku 10012 (o cualquier producto final), movemos todos nuestros ingredientes necesarios ya sea de recepcion o bodega hacia la cocina (todo tira status 200) y al momento de cocinar nos indica error de que no existen suficientes materias primas. 
Al monitorear la bodega de cocina mediante Postman durante el proceso, mientras se envian los productos, esta aumenta su numero de productos presentes. SIn embargo, al momento en que debiera cocinar esta disminuye aleatoriamente su capacidad (desaparecen los productos) y no se logra cocinar, pues devuelve el error de materias primas insuficientes. Al consultar los productos individualmente, estos indicaban una fecha de caducidad dentro de algunas horas, por lo que no debieron haber vencido.

![image](https://user-images.githubusercontent.com/11434052/59881005-7d5d3900-937c-11e9-8f40-ca7f548b16d2.png)
producto no vencido.

![image](https://user-images.githubusercontent.com/11434052/59880857-12136700-937c-11e9-8324-cc683c42241d.png)
bodega vacia, pero no se cocina lo requerido.

Este problema ha ocurrido al tratar de cocinar otros productos. Realmente no tenemos idea de que ocurre con los ingredientes y creemos que puede ser un error de la api. Saludos.

**Comment by arturokunder** [comment]
@afcerna me puedes enviar el archivo postman?

**Comment by arturokunder** [comment]
@afcerna es esto lo mismo que #71 ?

**Comment by FelipeApablaza** [comment]
<img width="560" alt="Captura de Pantalla 2019-06-21 a la(s) 10 15 10" src="https://user-images.githubusercontent.com/26126342/59928947-cd381080-940d-11e9-95e9-e7f3e68499e5.png">


Desde ayer nos sale esto en todos los request con metodo post.

**Comment by svergara1** [comment]
El error de @afcerna  creo que es el mismo error que en la issue #71 . Al tratar de producir en cocina, mandamos todos los ingredientes a cocina con status 200 (seguimos el flujo por horas buscando el error) pero luego nos sale el error de que faltan materias primas.

Adjunto console.log(error.response.data.detalles):

![Screen Shot 2019-06-20 at 9 57 32 PM](https://user-images.githubusercontent.com/26102385/59929704-66b3f200-940f-11e9-8641-0f96871ad180.png)

Dice que tenemos lo necesario en cocina pero no produce. Eso si, no se si le pasa al otro grupo que además elimina los ingredientes en cocina cuando trata de producir...
