### ISSUE TITLE
Limpiar Almacenes

### ISSUE THREAD

**Issue by silvamatias** [IIC3103/2019-proyecto#81]
Hola Profesor, es posible habilitar una función/opción para limpiar los almacenes en "dev" y dejarlos en 0 SKUs. Para esta entrega es necesario optimizar el uso del pulmón, por lo que esto sería de gran ayuda.

Muchas gracias!

**Comment by arturokunder** [comment]
Matías, como comenté antes, no es posible realizarlo, pero puedo borrar los productos de tu grupo

**Comment by silvamatias** [comment]
Ya, muchas gracias!

**Comment by arturokunder** [comment]
Matías, está todo vacío!
