### ISSUE TITLE
Error 500 usando API OC

### ISSUE THREAD

**Issue by cjgazali** [IIC3103/2019-proyecto#82]
<img width="560" alt="Captura de Pantalla 2019-06-21 a la(s) 10 15 10" src="https://user-images.githubusercontent.com/26126342/59928947-cd381080-940d-11e9-95e9-e7f3e68499e5.png">

Desde ayer nos sale esto en todos los request con metodo post. No alcanza a salir en la imagen, pero es un error 500.

_Originally posted by @FelipeApablaza in https://github.com/IIC3103/2019-proyecto/issues/80#issuecomment-504442800_

**Comment by cjgazali** [comment]
Creé esta issue para abordar este tema en específico. Confirmo que a nosotros nos pasa lo mismo.

![WhatsApp Image 2019-06-21 at 11 47 45](https://user-images.githubusercontent.com/20786646/59935119-15116480-941b-11e9-89e4-7312e346b036.jpeg)

**Comment by JoseRomeroi** [comment]
A nuestro grupo le pasa lo mismo

**Comment by jmsilva8** [comment]
A nuestro grupo también

**Comment by fsvergara** [comment]
A nuestro grupo tambien

**Comment by FelipeApablaza** [comment]
No se si al resto de los grupos les pasa, pero no están llegando pedidos ftp ni a desarrrollo, ni a producción. (grupo 12)

**Comment by arturokunder** [comment]
revisen ahora, creo que fue por espacio en la bd de desarrollo.
