### ISSUE TITLE
Espacio utilizado en bodega

### ISSUE THREAD

**Issue by jtagle2** [IIC3103/2019-proyecto#83]
Hoy día empezamos a pedir productos con mi grupo, y nos llegan en 8 horas. El problema, es que no tenemos ningún producto, pero al pedir los almacenes nos dice que tenemos espacio utilizado en recepción y cocina.
![image](https://user-images.githubusercontent.com/6934080/59949140-3e90b700-9440-11e9-9f70-4a6bb496b828.png)
Quizás es algo que hay que ver antes del monitoreo, porque no tenemos ningún producto al ver nuestros inventarios, pero igual tenemos recepción lleno y espacios de bodega pulmón utilizado.

Por un lado, que nos diga que la cocina está utilizada no nos va a dejar enviar a cocinar, porque no podremos poner los productos en cocina, y vamos a estar perdiendo plata por tener productos en pulmón, cuando en realidad no tenemos ninguno.

¿A alguien más le pasa?

**Comment by arturokunder** [comment]
@jtagle2 recuerda que a veces el `usedSpace` se puede descordinar en relación a la cantidad real utilizada.
En producción, este fenómeno se produce en mucho menor medida que en desarrollo, principalmente, debido a las capacidades de ambos servidores.
Ver #36 y #51

**Comment by jtagle2** [comment]
@arturokunder, 
Pero para medir el espacio se utilizará el used space? Porque si es así, creo que es importante revisar esto. No teníamos ningún producto (se estaban produciendo) y al parecer ya nos contaba estos en los inventarios. El problema, es que nos llegaban en 8 horas, por lo que tenemos 8 horas de bodega de pulmón con productos, sin la capacidad de moverlos a las otras bodegas (porque en realidad esos productos aún no existen)

**Comment by arturokunder** [comment]
No hay ninguna forma que se estén contando los productos aun no producidos (ya que al no estar producidos, ni siquiera se han creado en la bd).
Lo que puede haber hecho la diferencia es que hayas tenido productos vencidos en ese almacén, que como dije antes, en desarrollo se demora más en actualizarse, pero en producción, ese ajuste se produce mucho más rápido (10 mins máximo)

**Comment by jtagle2** [comment]
Ok. Gracias!
