### ISSUE TITLE
Problemas de producción de productos, llegada de ftp y creación de OC

### ISSUE THREAD

**Issue by FelipeApablaza** [IIC3103/2019-proyecto#84]
Grupo 12: 

No nos están llegando los productos que mandamos a producir.

No nos están llegando pedidos ftps ni a desarrollo ni a producción.

Requests post de ocs retornan error 500.

Esta es la situación desde jueves 20/jun

**Comment by arturokunder** [comment]
@FelipeApablaza 
Prueba ahora, resetie la bd para que tengan un ambiente limpio

**Comment by FelipeApablaza** [comment]
En producción seguimos sin recibir los pedidos ftps.
En desarrollo eso ya se arreglo.

**Comment by afcerna** [comment]
@arturokunder Desde ayer  sabado 22 en la tarde y a la hora de hoy domingo 23 a las 10 am, no estan llegando los productos en ambiente de desarrollo. Por favor, queremos trabajar hoydia! =)

**Comment by arturokunder** [comment]
@FelipeApablaza todavía no habilito producción. Les aviso cuando lo haga
