### ISSUE TITLE
Problemas para producir en desarrollo desde ayer

### ISSUE THREAD

**Issue by Zanfor** [IIC3103/2019-proyecto#87]
Hemos cotejado con varios grupos que desde ayer en la tarde (alrededor de las 16:00), los productos que se fabrican no están llegando ni a recepción ni a pulmón en el ambiente desarrollo. Esto ya fue mencionado entre los problemas de la #84 donde la única medida fue resetear la base de datos lo que al parecer no solucionó el problema de fondo. Favor revisar la situación de manera urgente para poder trabajar.

**Comment by Zanfor** [comment]
@arturokunder tio kunder aga argo

![tiokunder](https://user-images.githubusercontent.com/17620265/59978346-6b141280-95a9-11e9-8736-0bbf2253fdf6.png)

**Comment by arturokunder** [comment]
Zanfor, se estaba produciendo pero a una tasa muy baja.
No tiene relación con #84, ya que en ese caso se llenó la bd. Ahora era sólo una configuración que se me quedó atrás por las optimizaciones que estuve haciendo.
Ya se encuentra todo normalizado.

**Comment by svergara1** [comment]
Gracias. Por favor considere que empezó a ocurrir ayer en la tarde y no pudimos probar varias funcionalidades. @arturokunder

**Comment by arturokunder** [comment]
ok!

**Comment by arturokunder** [comment]
Por favor avisen lo antes posible para corregir a tiempo!

**Comment by Zanfor** [comment]
Empezaron a llegar de golpe hace unos minutos, gracias.

**Comment by svergara1** [comment]
Ahora por ejemplo el sku 1111 se esta demorando muchísimo en llegar. No se si será el mismo error de antes.

**Comment by svergara1** [comment]
@arturokunder
