### ISSUE TITLE
Funcionamiento Cocina

### ISSUE THREAD

**Issue by svergara1** [IIC3103/2019-proyecto#88]
Al intentar producir un producto final en cocina, si aún no se han mandados todos los ingredientes necesarios, nos indica correctamente el error de que no existen suficientes materias primas. Sin embargo, creemos que además se lleva los ingredientes que hay hasta el momento en cocina. 

Al imprimir error.response.data.detalles, sale que tenemos 3 de 1309 y 1 de 1307, pero luego desaparecen de cocina aun que no fueron utilizados para producir.

![Screen Shot 2019-06-23 at 12 23 43 PM](https://user-images.githubusercontent.com/26102385/59979159-f98c9200-95b1-11e9-9ade-56ae31071f20.png)

¿Podría revisar el codigo para confirmar cual es el funcionamiento al momento de cocinar?

**Comment by arturokunder** [comment]
Ok, revisaré!

**Comment by arturokunder** [comment]
Efectivamente, se van descontando las materias primas hasta cumplir con los requisitos, lo que quiere decir que si falla en algún punto por falta de materias primas, las anteriores ya se descontaron.
Si alcanzo, lo corrijo para que no sea así.

**Comment by acrojas2** [comment]
@arturokunder esto no sale en la documentación de la API.
