### ISSUE TITLE
Tamaño de lote kanikama

### ISSUE THREAD

**Issue by jpjoublan** [IIC3103/2019-proyecto#89]
Hola! Creo que hay un error con el tamaño de lote del kanikama, en el excel sale que es 5, pero cuando mandamos a producir nos dice que los lotes tienen que ser de 100. Creo que es mucho más logico que sean de 5, para no tener que pedir de a tantas unidades

**Comment by arturokunder** [comment]
@jpjoublan el Kanikama (sku 1005) tiene lote 5, tal como sale en el excel

**Comment by arturokunder** [comment]
Tienes algún request de ejemplo? (postman)

**Comment by jpjoublan** [comment]
![6cff234e-bb61-457e-85b4-8fa07cca50b6](https://user-images.githubusercontent.com/37160581/59982284-aa5c5680-95dd-11e9-8a1c-abb7f598abf9.jpg)

**Comment by arturokunder** [comment]
La api de la bodega no devuelve ese error. El error de problemas en los lotes es "Lote incorrecto (X unidades por lote)"

**Comment by jpjoublan** [comment]
Si era error nuestro, perdon! Gracias
