### ISSUE TITLE
Respuesta de GET /almacenes

### ISSUE THREAD

**Issue by nivek0o0** [IIC3103/2019-proyecto#9]
Hola,

¿por qué tenemos 2 bodegas que tienen los 4 booleanos en falso? Es decir, no son ni recepción, cocina, despacho o pulmón.

**Comment by arturokunder** [comment]
Kevin,
Como se explicó en clases, los almacenes que no son ni `recepcion`, ni `despacho`, ni `cocina`, ni `pulmon`, son de uso general, es decir, es espacio de almacenamiento libre, sin ninguna característica especial.
