### ISSUE TITLE
OC FTP desarrollo

### ISSUE THREAD

**Issue by acrojas2** [IIC3103/2019-proyecto#90]
@arturokunder  puede aumentar la frecuencia de ordenes de compra en el canal  FTP de desarrollo para testear las cosas?

**Comment by arturokunder** [comment]
Hecho, pero solo por un rato y en desarrollo.
De todas formas, si quieren probar estos flujos, basta que se creen una oc en la api, y guarden el archivo correspondiente en el ftp (pueden subir archivos)
