### ISSUE TITLE
Costo Uso Pulmón

### ISSUE THREAD

**Issue by silvamatias** [IIC3103/2019-proyecto#92]
Hola Profesor, agradeceríamos una explicación más en detalle sobre cómo nos cobrarán por el uso del pulmón.

En el enunciado dice $30 por producto por noche.
Esto quiere decir que se sacará un screenshot del pulmón a cierta hora cada día y sobre la cantidad total en uso se multiplica por 30? O cómo funciona lo de "por noche"?

En la entrega pasada ya no consideraban en la nota tener los stocks mínimos, podemos cambiarlos a nuestro gusto para disminuir el uso de espacios?

muchas gracias, saludos

**Comment by silvamatias** [comment]
Ademas, existen dos almacenes que no corresponden a despacho, recepcion, cocina o pulmón. Podemos usar estos almacenes para guardar cosas?

**Comment by arturokunder** [comment]
@silvamatias 

Esto quiere decir que se sacará un screenshot del pulmón a cierta hora cada día y sobre la cantidad total en uso se multiplica por 30
**Si, es exactamente eso**

En la entrega pasada ya no consideraban en la nota tener los stocks mínimos, podemos cambiarlos a nuestro gusto para disminuir el uso de espacios?
**Ahora tu defines los stocks mínimos a manejar**

Ademas, existen dos almacenes que no corresponden a despacho, recepcion, cocina o pulmón. Podemos usar estos almacenes para guardar cosas?
**solo se cobra pulmón. Los otros almacenes son de uso libre**
