### ISSUE TITLE
Problema con Rechazar_OC

### ISSUE THREAD

**Issue by vbarros2** [IIC3103/2019-proyecto#93]
Dentro de las funciones de ftp, esta rechazar_oc (en nuestro programa). Que cuando se le acaba el tiempo a una oc, la rechaza. Por alguna razón dejo de funcionar, lo probe manualmente y nada, retorna OK pero no rechaza la OC.

Dejo OC ejemplo "5d0ea784f26c4d00040d6377" que la he rechazado varias veces y nada.

Gracias

**Comment by arturokunder** [comment]
Vicente,
No las puedes rechazar porque aparece como `aceptada`.
Una vez aceptada, ya no se puede rechazar.

```json
{
    "_id": {
        "$oid": "5d0ea784f26c4d00040d6377"
    },
    "created_at": {
        "$date": "2019-06-22T22:11:16.465Z"
    },
    "updated_at": {
        "$date": "2019-06-22T22:11:16.465Z"
    },
    "cliente": "distribuidor",
    "proveedor": "5cbd31b7c445af0004739bed",
    "sku": "30005",
    "urlNotificacion": "",
    "estado": "aceptada",
    "fechaDespachos": [],
    "fechaEntrega": {
        "$date": "2019-06-22T23:41:00.000Z"
    },
    "precioUnitario": 9900,
    "cantidadDespachada": 0,
    "cantidad": 3,
    "canal": "ftp",
    "__v": 0
}
```
