### ISSUE TITLE
Caida API

### ISSUE THREAD

**Issue by RodrigoBocazG** [IIC3103/2019-proyecto#95]
@arturokunder Profe se le cayo la API!

**Comment by arturokunder** [comment]
Exactamente qué pasó? Me podrías dar más detalles?

**Comment by RodrigoBocazG** [comment]
Ya volvió. La api estaba respondiendo con 500 creo, la página de seguimiento tenía un application error, etc. Más detalle que eso no podría dar.

**Comment by arturokunder** [comment]
Si, el seguimiento de banco tiene un error. Pero es en el render de la página porque no.toma el caso cuando no hay datos.  
**Esto no afecta a la api**
Ya lo tengo corregido pero no lo he subido

**Comment by RodrigoBocazG** [comment]
Yo diría que sí se cayó la API. Dejo un screenshot de la consulta a /almacenes (siempre ocupo la misma).
![image](https://user-images.githubusercontent.com/11395569/60058450-7143e500-96b6-11e9-98a0-7656f212ce57.png)

**Comment by Zepk** [comment]
La api se encontraba definitivamente caida cuando se hizo la issue, todas las request retornaban errores.
