### ISSUE TITLE
IDs de órdenes aceptadas

### ISSUE THREAD

**Issue by bleon1** [IIC3103/2019-proyecto#97]
Hola profe @arturokunder , como está? Quería saber si existe la posibilidad de obtener todas las IDs de las órdenes de compra que mi grupo aceptó pero no finalizó. Esto para solucionar el problema que exista si viene de nuestro lado.
Saludos

**Comment by arturokunder** [comment]
No, no hay ningún método que te de esa información.
De forma excepcional, te puedo enviar estos datos tipo hora de almuerzo.
Escríbeme un correo porfa

**Comment by silvamatias** [comment]
Hola, a nosotros también nos gustaría tener esta información. Creo que si un grupo tuvo la opción, todos deberían.

saludos
