### ISSUE TITLE
Servidor FTP

### ISSUE THREAD

**Issue by seba608** [IIC3103/2019-proyecto#98]
Hola,

En nuestro servidor FTP siguen estando las órdenes de compra de la entrega pasada y cuando nuestro sistema pregunta por esos ids de órdenes de compra arroja error porque ya no existen en la base de datos. Para confirmar, ¿esos archivos serán borrados antes de las 18 para que desde esa hora solo hayan órdenes de esta entrega?

Saludos

**Comment by arturokunder** [comment]
Si! los borraré antes de comenzar a enviarlas

**Comment by arturokunder** [comment]
Ya está limpio el servidor. La oc comenzarán a llegar en unos minutos
